Repository eclipse-ecal/ecal, pull requests merged in 2023-11, with the labels that each got.

#1245 Doc: replaced continental links with eclipse-ecal
  doc/rst/license/thirdparty_licenses.rst
Labels: Auto Approve

#1249 doc/rst-fix
  doc/rst/advanced/layers/shm_zerocopy.rst
Labels: Auto Approve

#1252 Fixed wrong order of sender and receiver timestamp in make_frame() method
  contrib/measurement/base/include/ecal/measurement/imeasurement.h
Labels: bug, 5.11.7, 5.12.2

#1262 feature/udp-receive-thread-timing-configuration
  ecal/core/src/ecal_def.h
  ecal/core/src/ecal_registration_receiver.cpp
  ecal/core/src/io/rcv_sample.cpp
  ecal/core/src/io/rcv_sample.h
  ecal/core/src/mon/ecal_monitoring_threads.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader_udp_mc.cpp
Labels: enhancement
