Repository eclipse-ecal/ecal, pull requests merged in 2024-11, with the labels that each got.

#1777 [Readme.md] Updated supported operating systems
  README.md
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1780 service client connection state handling
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
Labels: cherry-pick-to-support/v5.13

#1787 [core] force symbol hiding for ecal_core(_c).so.
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/cimpl/ecal_time_cimpl.h
  ecal/core/include/ecal/ecal_client.h
  ecal/core/include/ecal/ecal_os.h
  ecal/core/include/ecal/ecal_publisher.h
  ecal/core/include/ecal/ecal_server.h
  ecal/core/include/ecal/ecal_subscriber.h
Labels: cherry-pick-to-NONE

#1789 [core] Remove ECAL_API occurrences in cpp files.
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/config/ecal_config_initializer.cpp
  ecal/core/src/registration/ecal_registration.cpp
Labels: cherry-pick-to-NONE

#1790 check event callback before execution
  ecal/service/ecal_service/src/client_session_impl_v0.cpp
  ecal/service/ecal_service/src/client_session_impl_v1.cpp
Labels: cherry-pick-to-NONE

#1791 [core][bugfix] attributes.unit_name not initialized.
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
Labels: cherry-pick-to-NONE

#1794 Added script for creating License reviews with the eclipse-dash-licensing-tool
  .gitignore
  scan-dependencies-with-dash.py
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1795 hotfix/memfile-ack-logic-deadlock
  ecal/core/src/io/shm/ecal_memfile_sync.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.h
Labels: cherry-pick-to-NONE

#1798 feature/chained pubsub
  ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
Labels: cherry-pick-to-NONE

#1807 Hotfix/host group feature
  ecal/core/src/config/builder/registration_attribute_builder.cpp
  ecal/core/src/registration/config/attributes/registration_attributes.h
  ecal/core/src/registration/config/attributes/sample_applier_attributes.h
  ecal/core/src/registration/config/builder/sample_applier_attribute_builder.cpp
  ecal/core/src/registration/ecal_registration_sample_applier.cpp
  ecal/core/src/registration/ecal_registration_sample_applier.h
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
Labels: cherry-pick-to-NONE

#1824 Fixed missing includes
  ecal/tests/cpp/clientserver_proto_test/src/clientserver_test_proto.cpp
  ecal/tests/cpp/clientserver_test/src/atomic_signalable.h
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/config_test/src/config_test.cpp
  ecal/tests/cpp/core_test/src/core_test.cpp
  ecal/tests/cpp/descgate_test/src/descgate_getentities.cpp
  ecal/tests/cpp/event_test/src/event_test.cpp
  ecal/tests/cpp/expmap_test/src/expmap_test.cpp
  ecal/tests/cpp/io_memfile_test/src/memfile_naming_test.cpp
  ecal/tests/cpp/io_memfile_test/src/memfile_test.cpp
  ecal/tests/cpp/logging_test/src/logging_test.cpp
  ecal/tests/cpp/monitoring_test/src/monitoring_filter_test.cpp
  ecal/tests/cpp/pubsub_proto_test/src/proto_dyn_subscriber_test.cpp
  ecal/tests/cpp/pubsub_proto_test/src/proto_publisher_test.cpp
  ecal/tests/cpp/pubsub_proto_test/src/proto_subscriber_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_acknowledge.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_multibuffer.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_udp.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp
  ecal/tests/cpp/serialization_test/src/common_generate.cpp
  ecal/tests/cpp/serialization_test/src/logging_serialization_test.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_serialization_test.cpp
  ecal/tests/cpp/serialization_test/src/parallel_serialization_test.cpp
  ecal/tests/cpp/serialization_test/src/payload_compare.cpp
  ecal/tests/cpp/serialization_test/src/payload_generate.cpp
  ecal/tests/cpp/serialization_test/src/payload_serialization_test.cpp
  ecal/tests/cpp/serialization_test/src/registration_serialization_test.cpp
  ecal/tests/cpp/serialization_test/src/service_serialization_test.cpp
  ecal/tests/cpp/topic2mcast_test/src/topic2mcast_test.cpp
  ecal/tests/cpp/util_test/src/expanding_vector_test.cpp
  ecal/tests/cpp/util_test/src/util_test.cpp
Labels: cherry-pick-to-NONE

#1827 [GH Actions] Removed macOS packing step
  .github/workflows/build-macos.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13
