Repository eclipse-ecal/ecal, pull requests merged in 2024-06, with the labels that each got.

#1623 [build] Reenable npcap support
  .github/workflows/build-windows.yml
Labels: cherry-pick-to-NONE

#1624 Feature/ubuntu 24 runner for 5.13 5.12
  .github/workflows/build-ubuntu-24.yml
Labels: cherry-pick-to-support/v5.12

#1627 Hotfix/macos build
  .github/workflows/build-macos.yml
Labels: cherry-pick-to-NONE

#1626 [core] expmap performance improvement
  ecal/core/src/util/ecal_expmap.h
  ecal/samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1631 [core] expmap performance improvement (#1626)
  ecal/core/src/util/ecal_expmap.h
  samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp
Labels: cherry-pick-to-NONE

#1616 Feature/csharp folder structure 2
  lang/csharp/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core.Samples/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core.Samples/pubsub_minimal_rec.cs
  lang/csharp/Continental.eCAL.Core.Samples/pubsub_minimal_rec_cb.cs
  lang/csharp/Continental.eCAL.Core.Samples/pubsub_minimal_snd.cs
  lang/csharp/Continental.eCAL.Core.Samples/service_minimal_client.cs
  lang/csharp/Continental.eCAL.Core.Samples/service_minimal_server.cs
  lang/csharp/Continental.eCAL.Core.Test/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core.Test/test.cs
  lang/csharp/Continental.eCAL.Core/AssemblyInfo.cpp
  lang/csharp/Continental.eCAL.Core/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core/ecal_clr.cpp
  lang/csharp/Continental.eCAL.Core/ecal_clr.h
  lang/csharp/Continental.eCAL.Protobuf.Samples.Datatypes/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf.Samples.Datatypes/animal.proto
  lang/csharp/Continental.eCAL.Protobuf.Samples.Datatypes/house.proto
  lang/csharp/Continental.eCAL.Protobuf.Samples.Datatypes/person.proto
  lang/csharp/Continental.eCAL.Protobuf.Samples.Datatypes/protobuf_csharp_helper.cmake
  lang/csharp/Continental.eCAL.Protobuf.Samples/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf.Samples/pubsub_person_rec.cs
  lang/csharp/Continental.eCAL.Protobuf.Samples/pubsub_person_rec_cb.cs
  lang/csharp/Continental.eCAL.Protobuf.Samples/pubsub_person_snd.cs
  lang/csharp/Continental.eCAL.Protobuf.Test/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf.Test/test.cs
  lang/csharp/Continental.eCAL.Protobuf/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf/ProtoHelper.cs
  lang/csharp/Continental.eCAL.Protobuf/ProtoPublisher.cs
  lang/csharp/Continental.eCAL.Protobuf/ProtoSubscriber.cs
  samples/csharp/CMakeLists.txt
  samples/csharp/pubsub/protobuf/protobuf/CMakeLists.txt
  samples/csharp/pubsub/string/minimal_rec/CMakeLists.txt
  samples/csharp/pubsub/string/minimal_rec_cb/CMakeLists.txt
  samples/csharp/pubsub/string/minimal_snd/CMakeLists.txt
  samples/csharp/services/minimal_client/CMakeLists.txt
  samples/csharp/services/minimal_server/CMakeLists.txt
  thirdparty/protobuf/build-protobuf.cmake
Labels: cherry-pick-to-NONE

#1632 [core] add/improved IsPublished/IsSubscribed logic (5.13.x)
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/ecal_reader.h
  testing/ecal/pubsub_test/src/pubsub_receive_test.cpp
Labels: cherry-pick-to-NONE

#1635 [CMake] Remove references to ${CMAKE_PROJECT_DIR} ...
  ecal/CMakeLists.txt
  ecal/tests/cpp/config_test/CMakeLists.txt
  ecal/tests/cpp/descgate_test/CMakeLists.txt
  ecal/tests/cpp/event_test/CMakeLists.txt
  ecal/tests/cpp/io_memfile_test/CMakeLists.txt
  ecal/tests/cpp/serialization_test/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1636 [core] Expmap takes additional template parameter for clock type.
  ecal/core/src/util/ecal_expmap.h
  ecal/tests/cpp/expmap_test/src/expmap_test.cpp
Labels: cherry-pick-to-NONE

#1639 const keyword removed from send() in publisher files
  ecal/core/include/ecal/ecal_publisher.h
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/samples/cpp/benchmarks/dynsize_snd/src/dynsize_snd.cpp
Labels: cherry-pick-to-NONE

#1637 [core] Refactoring / Renaming / Documentation of CExpMap
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.h
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/util/ecal_expmap.h
  ecal/tests/cpp/expmap_test/src/expmap_test.cpp
Labels: cherry-pick-to-NONE

#1633 [core] add/improved IsPublished/IsSubscribed logic (master)
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
Labels: cherry-pick-to-NONE

#1641 [sample] shutdown condition fixed
  ecal/samples/cpp/services/latency_client/src/latency_client.cpp
  ecal/samples/cpp/services/math_client/src/math_client.cpp
  ecal/samples/cpp/services/ping_client/src/ping_client.cpp
  ecal/samples/cpp/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13
