Repository eclipse-ecal/ecal, pull requests merged in 2024-03, with the labels that each got.

#1425 Backport v5.12
  ecal/core/src/ecal.cpp
Labels: Auto Approve

#1424 Backport v5.13
  ecal/core/src/ecal.cpp
Labels: Auto Approve

#1448 [GH Actions] Fixed typo in cherry-pick action
  .github/workflows/cherry-pick-to.yml
Labels: Auto Approve

#1451 [deployment] Removed setting of ECAL_DATA environment variable in inno setup
  cpack/innosetup/ecal_setup.iss.in
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1450 [GH Actions] Create cherry-pick-label-check.yml
  .github/workflows/cherry-pick-label-check.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1458 [GH Actions] Fixed cherry-pick-label-check action
  .github/workflows/cherry-pick-label-check.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1443 Doc/5 13 deprecation doc
  doc/rst/versions/5.13/compatibility_table.txt
  doc/rst/versions/5.13/deprecation.rst
  doc/rst/versions/5.13/whats_new.rst
Labels: cherry-pick-to-support/v5.13

#1461 [Doc] Downgraded empy due to incompatiblity with empy 4.0
  doc/requirements.txt
Labels: Auto Approve, cherry-pick-to-NONE

#1463 [Doc] Improved Sphinx Tabs in dark mode
  doc/rst/_static/css/tabs-3.4.5-ecaladdon.css
Labels: Auto Approve, cherry-pick-to-NONE

#1464 [doc] v5.13 deprecation.rst fixed
  doc/rst/versions/5.13/deprecation.rst
Labels: cherry-pick-to-support/v5.13

#1462 [core] Bugfix: descgate incorrectly locked with shared locks (master)
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1467 [Doc] Fixed malformed HTML code of page footer
  doc/rst/_templates/footer.html
Labels: cherry-pick-to-NONE

#1471 [core, test] set-get-unit-name
  app/rec/rec_tests/rec_rpc_tests/src/rec_cli_test.cpp
  ecal/tests/c/core_test/src/core_test.cpp
  ecal/tests/cpp/core_test/src/core_test.cpp
  ecal/tests/cpp/util_test/src/util_test.cpp
  tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
  tests/contrib/ecalproto/dynproto_test/src/dynproto_test.cpp
  tests/contrib/ecalproto/ecal_proto_test/src/test_filters.cpp
Labels: cherry-pick-to-NONE

#1478 [Doc] Documentation is now built from support/v5.13 branch
  .github/workflows/documentation.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1480 [Doc] Documentation is now built from support/v5.13 branch (#1478)
  .github/workflows/documentation.yml
Labels: Auto Approve

#1479 [Doc] Documentation is now built from support/v5.13 branch (#1478)
  .github/workflows/documentation.yml
Labels: Auto Approve

#1476 [core] description gate refactoring
  app/play/play_gui/src/main.cpp
  contrib/mma/src/mma_application.cpp
  ecal/core/include/ecal/cimpl/ecal_init_cimpl.h
  ecal/core/include/ecal/ecal_init.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/core/src/registration/ecal_registration_receiver.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/tests/CMakeLists.txt
  ecal/tests/cpp/clientserver_test/src/clientserver_getservices.cpp
  ecal/tests/cpp/util_test/src/util_test.cpp
Labels: cherry-pick-to-NONE

#1485 [core] changed shm preprocessor define usage
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
Labels: cherry-pick-to-NONE

#1488 [GH Actions] Added CHERRY_PICK_GITHUB_TOKEN to cherry-pick action
  .github/workflows/cherry-pick-to.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1495 [GH Actions] Fixed typos in cherry-pick-to workflow.
  .github/workflows/cherry-pick-to.yml
Labels: Auto Approve, cherry-pick-to-NONE
