Repository eclipse-ecal/ecal, pull requests merged in 2024-02, with the labels that each got.

#1346 [Core] Check validity of message drop event callback before actually calling it
  ecal/core/src/readwrite/ecal_reader.cpp
Labels: bug

#1358 [new-core-alignment] service includes cleaned up
  ecal/service/ecal_service/include/ecal/service/client_manager.h
  ecal/service/ecal_service/include/ecal/service/client_session.h
  ecal/service/ecal_service/include/ecal/service/server.h
  ecal/service/ecal_service/include/ecal/service/server_manager.h
  ecal/service/ecal_service/src/client_manager.cpp
  ecal/service/ecal_service/src/client_session.cpp
  ecal/service/ecal_service/src/client_session_impl_base.h
  ecal/service/ecal_service/src/client_session_impl_v0.cpp
  ecal/service/ecal_service/src/client_session_impl_v0.h
  ecal/service/ecal_service/src/client_session_impl_v1.cpp
  ecal/service/ecal_service/src/client_session_impl_v1.h
  ecal/service/ecal_service/src/log_helpers.h
  ecal/service/ecal_service/src/protocol_v0.cpp
  ecal/service/ecal_service/src/protocol_v0.h
  ecal/service/ecal_service/src/protocol_v1.cpp
  ecal/service/ecal_service/src/server.cpp
  ecal/service/ecal_service/src/server_impl.cpp
  ecal/service/ecal_service/src/server_impl.h
  ecal/service/ecal_service/src/server_manager.cpp
  ecal/service/ecal_service/src/server_session_impl_base.h
  ecal/service/ecal_service/src/server_session_impl_v0.cpp
  ecal/service/ecal_service/src/server_session_impl_v0.h
  ecal/service/ecal_service/src/server_session_impl_v1.cpp
  ecal/service/ecal_service/src/server_session_impl_v1.h
  ecal/service/test/src/ecal_tcp_service_test.cpp
Labels: refactoring

#1366 [GH PR Template] Added new template options for eCAL 5 / eCAL 5.13
  .github/pull_request_template.md
Labels: Auto Approve

#1362 [new-core-alignment] proto file cleanups part 3 (qos)
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/topic_widget.cpp
  app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp
  app/mon/mon_gui/src/widgets/models/topic_tree_item.h
  app/mon/mon_gui/src/widgets/models/topic_tree_model.h
  app/mon/mon_tui/src/model/data/topic.hpp
  app/mon/mon_tui/src/model/monitor.hpp
  app/mon/mon_tui/src/tui/view/topic_details.hpp
  app/mon/mon_tui/src/utils/string.hpp
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/cimpl/ecal_publisher_cimpl.h
  ecal/core/include/ecal/cimpl/ecal_qos_cimpl.h
  ecal/core/include/ecal/cimpl/ecal_subscriber_cimpl.h
  ecal/core/include/ecal/ecal.h
  ecal/core/include/ecal/ecal_clang.h
  ecal/core/include/ecal/ecal_publisher.h
  ecal/core/include/ecal/ecal_qos.h
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/include/ecal/ecalc.h
  ecal/core/src/ecal_clang.cpp
  ecal/core/src/ecalc.cpp
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_reader_layer.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/readwrite/ecal_writer_base.h
  ecal/core/src/readwrite/ecal_writer_info.h
  ecal/core/src/readwrite/inproc/ecal_writer_inproc.cpp
  ecal/core/src/readwrite/shm/ecal_reader_shm.h
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.h
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.h
  ecal/core/src/readwrite/tcp/ecal_writer_tcp.cpp
  ecal/core/src/readwrite/udp/ecal_reader_udp_mc.cpp
  ecal/core/src/readwrite/udp/ecal_reader_udp_mc.h
  ecal/core/src/readwrite/udp/ecal_writer_udp_mc.cpp
  ecal/core_pb/src/ecal/core/pb/topic.proto
  lang/python/core/src/ecal_wrap.cxx
  samples/cpp/benchmarks/multiple_snd/src/multiple_snd.cpp
  samples/cpp/monitoring/monitoring_rec/src/monitoring_rec.cpp
Labels: eCAL6

#1363 [new-core-alignment] proto file cleanups part 4 (padding, par_shm)
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core_pb/src/ecal/core/pb/layer.proto
Labels: eCAL6

#1361 [new-core-alignment] proto file cleanups part 2 (logging)
  CMakeLists.txt
  app/mon/mon_gui/src/widgets/log_widget/log_widget.cpp
  app/mon/mon_gui/src/widgets/models/log_model.cpp
  app/mon/mon_gui/src/widgets/models/log_model.h
  app/mon/mon_tui/src/model/log.hpp
  ecal/core/src/io/udp/ecal_udp_logging_receiver.h
  ecal/core/src/io/udp/ecal_udp_logging_sender.h
  ecal/core/src/logging/ecal_log_impl.cpp
  ecal/core/src/logging/ecal_log_impl.h
  ecal/core/src/monitoring/ecal_monitoring_def.cpp
  ecal/core_pb/CMakeLists.txt
  ecal/core_pb/src/ecal/core/pb/logging.proto
  ecal/core_pb/src/ecal/core/pb/monitoring.proto
  ecal/pb/CMakeLists.txt
  ecal/pb/include/ecal/pb/ecal.pb.h
  ecal/pb/include/ecal/pb/host.pb.h
  ecal/pb/include/ecal/pb/layer.pb.h
  ecal/pb/include/ecal/pb/mma/mma.pb.h
  ecal/pb/include/ecal/pb/monitoring.pb.h
  ecal/pb/include/ecal/pb/play/service.pb.h
  ecal/pb/include/ecal/pb/play/state.pb.h
  ecal/pb/include/ecal/pb/process.pb.h
  ecal/pb/include/ecal/pb/rec/client_service.pb.h
  ecal/pb/include/ecal/pb/rec/client_state.pb.h
  ecal/pb/include/ecal/pb/rec/server_service.pb.h
  ecal/pb/include/ecal/pb/rec/server_state.pb.h
  ecal/pb/include/ecal/pb/service.pb.h
  ecal/pb/include/ecal/pb/sim_time.pb.h
  ecal/pb/include/ecal/pb/sys/client_service.pb.h
  ecal/pb/include/ecal/pb/sys/service.pb.h
  ecal/pb/include/ecal/pb/sys/state.pb.h
  ecal/pb/include/ecal/pb/topic.pb.h
  ecal/pb/src/pb.cpp
  lang/python/core/src/ecal_wrap.cxx
Labels: eCAL6

#1367 [cmake, gh actions, batch] build cmake options and gh actions updated
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/build-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/ecal-fat-source.yml
  .github/workflows/pr-auto-approve.yml
  build_win/download_npcap.ps1
  build_win/win_make_cmake.bat
Labels: bug

#1369 [GH Actions] Documentation workflow now uses the modern HAS_QT option
  .github/workflows/documentation.yml
Labels: Auto Approve

#1372 [mma] cleaned includes
  contrib/mma/include/linux/mma_linux.h
  contrib/mma/include/linux/pipe_refresher.h
  contrib/mma/include/logger.h
  contrib/mma/src/linux/mma_linux.cpp
  contrib/mma/src/linux/pipe_refresher.cpp
  contrib/mma/src/logger.cpp
  contrib/mma/src/mma.cpp
  contrib/mma/src/mma_application.cpp
  contrib/mma/src/query_manager.cpp
  contrib/mma/src/zombie_instance_killer.cpp
Labels: Auto Approve

#1382 package.xml: Bumped version number to 6.0.0
  package.xml
Labels: Auto Approve

#1386 [GH PR Template] Removed master-v5
  .github/pull_request_template.md
Labels: Auto Approve

#1385 [play] fix crash when playing empty measurements.
  app/play/play_core/src/measurement_container.cpp
Labels: cherry-pick-v5.12, cherry-pick-v5.13

#1392 [CMake / Cpack] replaces deprecated exec_program with execute_process
  cpack/innosetup.cmake
Labels: Auto Approve

#1391 [Core / Process Stub] Added missing C++14 requirement in CMakeLists.txt
  ecal/core/CMakeLists.txt
Labels: Auto Approve
