Repository eclipse-ecal/ecal, pull requests merged in 2024-05, with the labels that each got.

#1579 [Core / Service]: Fixed crash that occured when communicating with eCAL 5.12 services
  ecal/service/ecal_service/src/server_session_impl_v0.cpp
  ecal/service/ecal_service/src/server_session_impl_v0.h
  ecal/service/test/src/ecal_tcp_service_test.cpp
Labels: cherry-pick-to-support/v5.13

#1585 [build] reactivate capnproto and flatbuffers samples
  samples/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec_cb/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec_dynamic/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_snd/CMakeLists.txt
  samples/cpp/pubsub/flatbuffer/monster_rec/CMakeLists.txt
  samples/cpp/pubsub/flatbuffer/monster_snd/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1454 [python] Scikit-build-core driven wheel creation
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/build-windows.yml
  .github/workflows/build_wheels.yml
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  app/app_pb/CMakeLists.txt
  cmake/helper_functions/ecal_python_functions.cmake
  contrib/ecaltime/ecaltime_pb/CMakeLists.txt
  ecal/core_pb/CMakeLists.txt
  lang/python/CMakeLists.txt
  lang/python/core/CMakeLists.txt
  lang/python/ecalhdf5/CMakeLists.txt
  lang/python/setup.py.in
  pyproject.toml
Labels: cherry-pick-to-NONE

#1571 [GH Actions] Cleaned Windows and Ubuntu Actions
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  README.md
Labels: cherry-pick-to-NONE

#1592 [Core, Services, Protobuf] Fixed compatibility with Ubuntu 18.04 (gcc7 / protobuf 3.0)
  ecal/core_pb/src/ecal/core/pb/ecal.proto
  ecal/core_pb/src/ecal/core/pb/layer.proto
  ecal/service/ecal_service/src/client_session_impl_v0.cpp
  ecal/service/ecal_service/src/client_session_impl_v1.cpp
Labels: cherry-pick-to-NONE

#1591 [Mon / Qt Apps] Fixed filter-function
  lib/CustomQt/src/QMulticolumnSortFilterProxyModel.cpp
Labels: cherry-pick-to-support/v5.13

#1595 [.clangtidy] Disabled readability-use-anyofallof warning
  .clang-tidy
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1598 [Rec] Fixed "Recording" display bug and some other bugs
  app/rec/rec_gui/src/widgets/recording_history_widget/job_history_model.cpp
  app/rec/rec_gui/src/widgets/wait_for_shutdown_dialog/wait_for_shutdown_dialog.cpp
  app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1601 [core, service] service log level changed from info to debug1
  ecal/core/src/service/ecal_service_singleton_manager.cpp
Labels: cherry-pick-to-NONE

#1582 Template class for CMessageSubscriber (instead of CMsgSubscriber)
  app/mon/mon_cli/CMakeLists.txt
  app/mon/mon_cli/src/ecal_mon_cli.cpp
  app/mon/mon_plugins/capnproto_reflection/CMakeLists.txt
  app/mon/mon_plugins/protobuf_reflection/CMakeLists.txt
  app/mon/mon_plugins/protobuf_reflection/src/plugin_widget.cpp
  app/mon/mon_plugins/protobuf_reflection/src/plugin_widget.h
  app/mon/mon_plugins/signals_plotting/CMakeLists.txt
  app/mon/mon_plugins/signals_plotting/src/plugin_widget.cpp
  app/mon/mon_plugins/signals_plotting/src/plugin_widget.h
  app/mon/mon_tui/src/tui/view/message_visualization/proto_tree.hpp
  app/mon/mon_tui/src/tui/viewmodel/message_visualization/proto.hpp
  ecal/core/include/ecal/ecal_types.h
  ecal/core/include/ecal/msg/capnproto/dynamic.h
  ecal/core/include/ecal/msg/capnproto/subscriber.h
  ecal/core/include/ecal/msg/dynamic.h
  ecal/core/include/ecal/msg/flatbuffers/subscriber.h
  ecal/core/include/ecal/msg/messagepack/subscriber.h
  ecal/core/include/ecal/msg/protobuf/client.h
  ecal/core/include/ecal/msg/protobuf/dynamic_subscriber.h
  ecal/core/include/ecal/msg/protobuf/server.h
  ecal/core/include/ecal/msg/protobuf/subscriber.h
  ecal/core/include/ecal/msg/string/subscriber.h
  ecal/core/include/ecal/msg/subscriber.h
  ecal/samples/cpp/pubsub/protobuf/person_rec/CMakeLists.txt
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/CMakeLists.txt
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/src/proto_dyn_rec.cpp
  ecal/tests/cpp/pubsub_proto_test/CMakeLists.txt
  ecal/tests/cpp/pubsub_proto_test/src/proto_dyn_subscriber_test.cpp
  samples/cpp/pubsub/capnp/addressbook_rec/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec/src/addressbook_rec.cpp
  samples/cpp/pubsub/capnp/addressbook_rec_cb/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec_dynamic/CMakeLists.txt
  samples/cpp/pubsub/capnp/addressbook_rec_dynamic/src/addressbook_rec_dynamic.cpp
  samples/cpp/pubsub/capnp/addressbook_snd/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1604 [core] subscriber configuration
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/ecal_publisher_config.h
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/include/ecal/ecal_subscriber_config.h
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/io/shm/ecal_memfile_db.cpp
  ecal/core/src/io/shm/ecal_memfile_db.h
  ecal/core/src/io/shm/ecal_memfile_pool.cpp
  ecal/core/src/io/shm/ecal_memfile_pool.h
  ecal/core/src/logging/ecal_log_impl.cpp
  ecal/core/src/logging/ecal_log_impl.h
  ecal/core/src/monitoring/ecal_monitoring_def.cpp
  ecal/core/src/monitoring/ecal_monitoring_def.h
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_pubgate.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_config.cpp
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/core/src/registration/ecal_registration_receiver.h
  ecal/core/src/time/ecal_timegate.cpp
  ecal/core/src/time/ecal_timegate.h
Labels: cherry-pick-to-NONE

#1606 [core] send frequency calculation fixed in case of unconnected publisher
  ecal/core/src/readwrite/ecal_writer.cpp
Labels: cherry-pick-to-support/v5.13

#1605 [core] Move eCAL::protobuf::CDynamicJSONSubscriber
  ecal/core/include/ecal/msg/protobuf/dynamic_json_subscriber.h
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_json_rec/CMakeLists.txt
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_json_rec/src/proto_dyn_json_rec.cpp
Labels: cherry-pick-to-NONE

#1608 send frequency calculation fixed in case of unconnected publisher
  ecal/core/src/readwrite/ecal_writer.cpp
Labels: cherry-pick-to-NONE

#1610 [c#] Do not reuse Protobuf message objects in callbacks
  lang/csharp/Continental/eCAL/Protobuf/ProtoSubscriber.cs
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1617 [GH] Adding Ubuntu 24.04 to GH workflows
  .github/workflows/build-ubuntu.yml
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1619 Update build-windows.yml
  .github/workflows/build-windows.yml
Labels: cherry-pick-to-NONE
