Repository eclipse-ecal/ecal, pull requests merged in 2024-07, with the labels that each got.

#1650 [core] Fix bug in frequency calculator that will reset the frequency to 0.0 even though data is still incoming.
  ecal/core/src/util/frequency_calculator.h
  ecal/tests/cpp/util_test/src/util_test.cpp
Labels: cherry-pick-to-support/v5.13

#1647 Feature/registration provider refactoring
  ecal/core/CMakeLists.txt
  ecal/core/src/registration/ecal_process_registration.cpp
  ecal/core/src/registration/ecal_process_registration.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/registration/ecal_registration_sender.h
  ecal/core/src/registration/ecal_registration_sender_shm.cpp
  ecal/core/src/registration/ecal_registration_sender_shm.h
  ecal/core/src/registration/ecal_registration_sender_udp.cpp
  ecal/core/src/registration/ecal_registration_sender_udp.h
Labels: cherry-pick-to-NONE

#1656 [core] innosetup-configuration-path-fix
  cpack/innosetup/ecal_setup.iss.in
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1659 [gh-actions] kill-xprotect-scan-macos
  .github/workflows/build-macos.yml
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1655 [config] cleanup
  ecal/core/include/ecal/config/publisher.h
  ecal/core/include/ecal/config/subscriber.h
  ecal/core/include/ecal/config/transport_layer.h
  ecal/core/include/ecal/ecal_config.h
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/config/ecal_config_initializer.cpp
  ecal/tests/cpp/config_test/src/config_test.cpp
Labels: cherry-pick-to-NONE

#1664 sync-with-ecal-core-2024-07-17
  ecal/core/CMakeLists.txt
  ecal/core/src/config/ecal_cmd_parser.cpp
  ecal/core/src/config/ecal_config_reader.cpp
  ecal/tests/cpp/config_test/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1662 Feature/registration receiver logic
  ecal/core/CMakeLists.txt
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/core/src/registration/ecal_registration_receiver.h
  ecal/core/src/registration/ecal_registration_types.h
  ecal/core/src/registration/shm/ecal_registration_receiver_shm.cpp
  ecal/core/src/registration/shm/ecal_registration_receiver_shm.h
  ecal/core/src/registration/shm/ecal_registration_sender_shm.cpp
  ecal/core/src/registration/shm/ecal_registration_sender_shm.h
  ecal/core/src/registration/udp/ecal_registration_receiver_udp.cpp
  ecal/core/src/registration/udp/ecal_registration_receiver_udp.h
  ecal/core/src/registration/udp/ecal_registration_sender_udp.cpp
  ecal/core/src/registration/udp/ecal_registration_sender_udp.h
Labels: cherry-pick-to-NONE

#1547 [gh actions] update setup-python action for macos
  .github/workflows/build-macos.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1665 [core] new-pub-sub-matching-compatibility-5
  ecal/core/CMakeLists.txt
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_transport_layer.h
  ecal/core/src/readwrite/ecal_writer.cpp
Labels: cherry-pick-to-NONE

#1666 [sample] benchmark-sample-massive_pub_sub-added
  samples/CMakeLists.txt
  samples/cpp/benchmarks/massive_pub_sub/CMakeLists.txt
  samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
Labels: cherry-pick-to-NONE

#1667 [core] registration-loopback-logic-fixed-for-service-registrations
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/core/src/registration/ecal_registration_receiver.h
  ecal/tests/cpp/clientserver_proto_test/src/clientserver_test_proto.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
Labels: cherry-pick-to-NONE

#1671 [core] active-registration-logic-getter
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_pubgate.h
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/pubsub/ecal_subgate.h
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_servicegate.cpp
  ecal/core/src/service/ecal_servicegate.h
  ecal/tests/cpp/util_test/src/util_gettopics.cpp
Labels: cherry-pick-to-NONE

#1673 [core] serialization-decode-error-handling
  ecal/core/src/serialization/ecal_serialize_logging.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_payload.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_serialize_service.cpp
Labels: cherry-pick-to-NONE

#1674 [core] registration-sender-datarace-fix
  ecal/core/src/registration/shm/ecal_registration_sender_shm.cpp
  ecal/core/src/registration/shm/ecal_registration_sender_shm.h
  ecal/core/src/registration/udp/ecal_registration_sender_udp.cpp
  ecal/core/src/registration/udp/ecal_registration_sender_udp.h
Labels: cherry-pick-to-NONE

#1677 [core] registration-provider-refactoring
  ecal/core/cfg/ecal.yaml
  ecal/core/src/config/default_config.h
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/registration/ecal_registration_sample_applier.cpp
  ecal/core/src/registration/ecal_registration_sample_applier.h
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/util/ecal_thread.h
  ecal/tests/cpp/util_test/src/util_getclients.cpp
  ecal/tests/cpp/util_test/src/util_getservices.cpp
  ecal/tests/cpp/util_test/src/util_gettopics.cpp
Labels: cherry-pick-to-NONE

#1678 [build] ensure compatibility with yaml-cpp < 0.8.0
  app/meas_cutter/CMakeLists.txt
  ecal/core/CMakeLists.txt
  ecal/tests/cpp/config_test/CMakeLists.txt
  thirdparty/yaml-cpp/compatibility-yaml-cpp.cmake
Labels: cherry-pick-to-NONE

#1681 [core] Protobuf Publisher Send should return the actual send size.
  ecal/core/include/ecal/msg/protobuf/publisher.h
  ecal/tests/cpp/pubsub_proto_test/src/proto_subscriber_test.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1683 [core] zero-copy-zero-payload-shm-transfer
  ecal/core/src/io/shm/ecal_memfile_pool.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13
