Repository eclipse-ecal/ecal, pull requests merged in 2024-09, with the labels that each got.

#1726 [core] 2 tests renamed
  ecal/tests/cpp/config_test/src/config_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
Labels: cherry-pick-to-NONE

#1703 [python] python-monitoring-json-sample-added
  samples/CMakeLists.txt
  samples/python/monitoring/monitoring_json/CMakeLists.txt
  samples/python/monitoring/monitoring_json/monitoring_json.py
  samples/python/monitoring/monitoring_json/monitoring_json.pyproj
Labels: cherry-pick-to-NONE

#1727 [config] Move complete memfile config to publisher
  doc/rst/configuration/options.rst
  doc/rst/configuration/runtime_configuration.rst
  doc/rst/configuration/src/hello_config/main.cpp
  ecal/core/include/ecal/config/publisher.h
  ecal/core/include/ecal/config/transport_layer.h
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/configuration_to_yaml.h
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
Labels: cherry-pick-to-NONE

#1728 Hotfix/innosetup config path handling
  cpack/innosetup/ecal_setup.iss.in
Labels: cherry-pick-to-NONE

#1729 [core] new-datarw-connection-logic
  cpack/innosetup/ecal_setup.iss.in
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/tests/cpp/pubsub_test/CMakeLists.txt
  ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
Labels: cherry-pick-to-NONE

#1730 [protobuf] Improved protobuf reflection for empty submessages
  ecal/msg/protobuf/src/ecal_proto_decoder.cpp
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/src/proto_dyn_rec.cpp
Labels: cherry-pick-to-support/v5.13

#1732 [core] ecal_config.h added to visual studio project
  ecal/core/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1733 [core] ecal sample logic massive_pub_sub aligned with master
  cpack/innosetup/ecal_setup.iss.in
  samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
Labels: cherry-pick-to-NONE

#1734 [protobuf] Readded msg_size and field name check to ProcProtoMsg recursion
  ecal/msg/protobuf/src/ecal_proto_decoder.cpp
  ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/src/proto_dyn_rec.cpp
Labels: cherry-pick-to-support/v5.13

#1719 [core] Make STopicId available in subscriber callbacks
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/include/ecal/ecal_publisher.h
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/include/ecal/ecal_types.h
  ecal/core/src/io/shm/ecal_memfile_pool.cpp
  ecal/core/src/io/shm/ecal_memfile_pool.h
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/pubsub/ecal_subgate.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/readwrite/shm/ecal_reader_shm.cpp
  ecal/core/src/readwrite/shm/ecal_reader_shm.h
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp
  ecal/core/src/readwrite/tcp/ecal_writer_tcp.cpp
  ecal/core/src/readwrite/udp/ecal_writer_udp.cpp
  ecal/core/src/serialization/ecal_serialize_sample_payload.cpp
  ecal/core/src/serialization/ecal_struct_sample_payload.h
  ecal/samples/cpp/benchmarks/many_connections_rec/src/many_connections_rec.cpp
  ecal/tests/cpp/pubsub_test/CMakeLists.txt
  ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp
  ecal/tests/cpp/serialization_test/src/payload_compare.cpp
  ecal/tests/cpp/serialization_test/src/payload_generate.cpp
Labels: cherry-pick-to-NONE

#1736 [core] provide SDataTypeInformation in callbacks
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/serialization/ecal_struct_sample_registration.h
  ecal/samples/cpp/benchmarks/many_connections_rec/src/many_connections_rec.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp
Labels: cherry-pick-to-NONE

#1737 [build] Enable wheel build on branch master
  .github/workflows/build_wheels.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1741 [python] Updated wheel build
  .github/workflows/build_wheels.yml
  pyproject.toml
Labels: cherry-pick-to-NONE

#1742 [core] minor performance improvements
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/util/ecal_expmap.h
Labels: cherry-pick-to-NONE

#1743 [python] Bugfix mon_monitoring() crash
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1744 [core] Reduce allocation / deallocations necessary for Registration.
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/ecal_types.h
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/ecal_reader.cpp
  ecal/core/src/readwrite/ecal_reader.h
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_provider.h
  ecal/core/src/registration/shm/ecal_registration_receiver_shm.cpp
  ecal/core/src/registration/shm/ecal_registration_receiver_shm.h
  ecal/core/src/registration/udp/ecal_registration_sender_udp.cpp
  ecal/core/src/serialization/ecal_serialize_common.cpp
  ecal/core/src/serialization/ecal_serialize_common.h
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_struct_sample_common.h
  ecal/core/src/serialization/ecal_struct_sample_registration.h
  ecal/core/src/serialization/ecal_struct_service.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_servicegate.cpp
  ecal/core/src/util/expanding_vector.h
  ecal/tests/cpp/serialization_test/src/registration_compare.cpp
  ecal/tests/cpp/serialization_test/src/registration_serialization_test.cpp
  ecal/tests/cpp/util_test/CMakeLists.txt
  ecal/tests/cpp/util_test/src/expanding_vector_test.cpp
Labels: cherry-pick-to-NONE

#1746 [MonGUI] minor performance improvements.
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/ecalmon_tree_widget.cpp
  app/mon/mon_gui/src/widgets/models/host_tree_item.cpp
  app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp
  app/mon/mon_gui/src/widgets/visualisation_widget/visualisation_widget.cpp
Labels: cherry-pick-to-NONE
