Repository eclipse-ecal/ecal, pull requests merged in 2024-04, with the labels that each got.

#1493 [core] [gui] Basic monitoring support for client entities
  app/mon/mon_gui/CMakeLists.txt
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/service_widget.cpp
  app/mon/mon_gui/src/widgets/models/service_tree_item.cpp
  app/mon/mon_gui/src/widgets/models/service_tree_item.h
  app/mon/mon_gui/src/widgets/models/service_tree_model.cpp
  app/mon/mon_gui/src/widgets/models/service_tree_model.h
  ecal/core/include/ecal/ecal_client.h
  ecal/core/include/ecal/ecal_service_info.h
  ecal/core/include/ecal/msg/protobuf/client.h
  ecal/core/include/ecal/msg/protobuf/ecal_proto_dyn.h
  ecal/core/include/ecal/msg/protobuf/server.h
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_struct_service.h
  ecal/core/src/serialization/nanopb/service.pb.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core_pb/src/ecal/core/pb/service.proto
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  ecal/tests/cpp/serialization_test/src/registration_compare.cpp
  ecal/tests/cpp/serialization_test/src/registration_generate.cpp
Labels: cherry-pick-to-NONE

#1500 [Launcher GUI] Removed Font and replaced it with SVGs.
  app/util/launcher/resources/NEURPOLI.TTF
  app/util/launcher/resources/labels/exit.svg
  app/util/launcher/resources/labels/info.svg
  app/util/launcher/resources/labels/logo.svg
  app/util/launcher/resources/labels/monitor.svg
  app/util/launcher/resources/labels/play.svg
  app/util/launcher/resources/labels/rec.svg
  app/util/launcher/resources/labels/src/button_image_as_layers.svg
  app/util/launcher/resources/labels/src/button_text_as_layers.svg
  app/util/launcher/resources/labels/sys.svg
  app/util/launcher/resources/resources.qrc
  app/util/launcher/src/main.cpp
  app/util/launcher/src/main_window.ui
  cpack/innosetup/gfx/NEURPOLI.TTF
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1498 [QWT cmake] Fixed variable reuse of QWT_LIBRARY_TYPE
  thirdparty/qwt/CMakeLists.txt
Labels: Auto Approve, cherry-pick-to-NONE

#1501 Feature/dependency providers
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/build-windows.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  CMakePresets.json
  build_win/win_make_cmake.bat
  cmake/helper_functions/ecal_helper_functions.cmake
  cmake/submodule_dependencies.cmake
  thirdparty/asio/Modules/Findasio.cmake
  thirdparty/asio/build-asio.cmake
  thirdparty/cmakefunctions/Modules/FindCMakeFunctions.cmake
  thirdparty/cmakefunctions/build-cmakefunctions.cmake
  thirdparty/curl/Modules/FindCURL.cmake
  thirdparty/curl/build-curl.cmake
  thirdparty/fineftp/Modules/Findfineftp.cmake
  thirdparty/fineftp/build-fineftp.cmake
  thirdparty/ftxui/Modules/Findftxui.cmake
  thirdparty/ftxui/build-ftxui.cmake
  thirdparty/gtest/Modules/FindGTest.cmake
  thirdparty/gtest/build-gtest.cmake
  thirdparty/hdf5/Modules/FindHDF5.cmake
  thirdparty/hdf5/build-hdf5.cmake
  thirdparty/libssh2/Modules/Findlibssh2.cmake
  thirdparty/libssh2/build-libssh2.cmake
  thirdparty/protobuf/Modules/FindProtobuf.cmake
  thirdparty/protobuf/build-protobuf.cmake
  thirdparty/qwt/Modules/Findqwt.cmake
  thirdparty/qwt/build-qwt.cmake
  thirdparty/recycle/Modules/Findrecycle.cmake
  thirdparty/recycle/build-recycle.cmake
  thirdparty/simpleini/CMakeLists.txt
  thirdparty/simpleini/Modules/Findsimpleini.cmake
  thirdparty/simpleini/build-simpleini.cmake
  thirdparty/spdlog/Modules/Findspdlog.cmake
  thirdparty/spdlog/build-spdlog.cmake
  thirdparty/tclap/CMakeLists.txt
  thirdparty/tclap/Modules/Findtclap.cmake
  thirdparty/tclap/build-tclap.cmake
  thirdparty/tcp_pubsub/Modules/Findtcp_pubsub.cmake
  thirdparty/tcp_pubsub/build-tcp_pubsub.cmake
  thirdparty/termcolor/Modules/Findtermcolor.cmake
  thirdparty/termcolor/build-termcolor.cmake
  thirdparty/tinyxml2/Modules/Findtinyxml2.cmake
  thirdparty/tinyxml2/build-tinyxml2.cmake
  thirdparty/udpcap/Modules/Findudpcap.cmake
  thirdparty/udpcap/build-udpcap.cmake
  thirdparty/yaml-cpp/Modules/Findyaml-cpp.cmake
  thirdparty/yaml-cpp/build-yaml-cpp.cmake
  thirdparty/zlib/Modules/Findzlib.cmake
  thirdparty/zlib/build-zlib.cmake
Labels: cherry-pick-to-NONE

#1513 [cmake] quotation marks removed from submodule_dependencies.cmake
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/documentation.yml
  build_win/win_make_cmake.bat
Labels: cherry-pick-to-NONE

#1514 [core/test] util_test (ParallelGetTopics) was excluded due to incorrect CMake setting
  ecal/tests/CMakeLists.txt
  ecal/tests/cpp/util_test/src/util_test.cpp
Labels: cherry-pick-to-NONE

#1516 [gh-actions] fix clang-tidy review with dependency providers.
  .github/workflows/clang-tidy-review.yml
Labels: cherry-pick-to-NONE

#1515 Convert defines to constexpr
  ecal/core/src/config/ecal_config_reader.cpp
  ecal/core/src/config/ecal_config_reader.h
  ecal/core/src/ecal_def.h
  ecal/core/src/ecal_def_ini.h
Labels: cherry-pick-to-NONE

#1523 Hotfix/macos downgrade protobuf
  .github/workflows/build-macos.yml
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1535 [dependencies] Add Protobuf 3.26 support to eCAL. (#1530)
  .github/workflows/build-macos.yml
  contrib/ecalproto/src/ecal_proto_dyn.cpp
  ecal/core/src/pubsub/ecal_proto_dyn_json_sub.cpp
Labels: Auto Approve

#1534 [gh actions] Please also build PRs on this branch!
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu-20.yml
  .github/workflows/build-ubuntu-22.yml
  .github/workflows/build-windows.yml
Labels: Auto Approve

#1537 [dependencies] ensure Protobuf 3.26 compatibility.
  .github/workflows/build-macos.yml
  ecal/core/include/ecal/msg/protobuf/dynamic_json_subscriber.h
  ecal/msg/protobuf/src/ecal_proto_dyn.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#1541 [doc] downgrade Sphinx to < 7.3
  doc/requirements.txt
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1544 [core] sync with ecal core 2024 04 17
  ecal/tests/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1538 new - ecaludp based - udp send/receive handling
  ecal/core/CMakeLists.txt
  ecal/core/src/ecal_process.cpp
  ecal/core/src/io/udp/ecal_udp_configurations.cpp
  ecal/core/src/io/udp/ecal_udp_configurations.h
  ecal/core/src/io/udp/ecal_udp_receiver_attr.h
  ecal/core/src/io/udp/ecal_udp_sample_receiver.cpp
  ecal/core/src/io/udp/ecal_udp_sample_receiver.h
  ecal/core/src/io/udp/ecal_udp_sample_receiver_asio.cpp
  ecal/core/src/io/udp/ecal_udp_sample_receiver_asio.h
  ecal/core/src/io/udp/ecal_udp_sample_receiver_base.h
  ecal/core/src/io/udp/ecal_udp_sample_receiver_npcap.cpp
  ecal/core/src/io/udp/ecal_udp_sample_receiver_npcap.h
  ecal/core/src/io/udp/ecal_udp_sample_sender.cpp
  ecal/core/src/io/udp/ecal_udp_sample_sender.h
  ecal/core/src/io/udp/ecal_udp_sender_attr.h
  ecal/core/src/io/udp/fragmentation/msg_type.h
  ecal/core/src/io/udp/fragmentation/rcv_fragments.cpp
  ecal/core/src/io/udp/fragmentation/rcv_fragments.h
  ecal/core/src/io/udp/fragmentation/snd_fragments.cpp
  ecal/core/src/io/udp/linux/socket_os.h
  ecal/core/src/io/udp/sendreceive/udp_receiver.cpp
  ecal/core/src/io/udp/sendreceive/udp_receiver.h
  ecal/core/src/io/udp/sendreceive/udp_receiver_asio.cpp
  ecal/core/src/io/udp/sendreceive/udp_receiver_asio.h
  ecal/core/src/io/udp/sendreceive/udp_receiver_npcap.cpp
  ecal/core/src/io/udp/sendreceive/udp_receiver_npcap.h
  ecal/core/src/io/udp/sendreceive/udp_sender.cpp
  ecal/core/src/io/udp/sendreceive/udp_sender.h
  ecal/core/src/logging/ecal_log_impl.cpp
  ecal/core/src/readwrite/udp/ecal_reader_udp_mc.cpp
  ecal/core/src/readwrite/udp/ecal_writer_udp_mc.cpp
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
Labels: cherry-pick-to-NONE

#1554 [Mon] Fix service collisions on ecal_mon_gui (master)
  app/mon/mon_gui/src/widgets/models/service_tree_item.h
Labels: Auto Approve, cherry-pick-to-NONE

#1555 [Mon] Fix service collisions on ecal_mon_gui (5.12)
  app/mon/mon_gui/src/widgets/models/service_tree_item.cpp
Labels: Auto Approve

#1558 [Core] Fixed Udpcap warning
  ecal/core/src/io/udp/sendreceive/udp_receiver_npcap.cpp
Labels: Auto Approve

#1562 downgrade macos version.
  .github/workflows/build-macos.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1560 [GH Actions] Removed Code-sign action with self-signed certificate
  .github/workflows/build-windows.yml
Labels: Auto Approve, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1567 Added iostream to ecal_udp_sample_receiver.cpp source.
  ecal/core/src/io/udp/ecal_udp_sample_receiver.cpp
Labels: cherry-pick-to-NONE

#1568 [app] ecalmon layer detection logic
  app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp
  app/mon/mon_tui/src/model/monitor.hpp
Labels: cherry-pick-to-NONE

#1569 [CMake] Added CMAKE_POSITION_INDEPENDENT_CODE ON to qt relevant builds
  app/mon/mon_plugins/monitor_tree_view/CMakeLists.txt
  lib/CustomQt/CMakeLists.txt
  lib/CustomTclap/CMakeLists.txt
  lib/QEcalParser/CMakeLists.txt
  lib/ThreadingUtils/CMakeLists.txt
  lib/ecal_utils/CMakeLists.txt
  thirdparty/qwt/CMakeLists.txt
Labels: cherry-pick-to-support/v5.13

#1573 [core] writer refactoring based on unique ptr
  ecal/core/src/readwrite/ecal_writer.cpp
  ecal/core/src/readwrite/ecal_writer.h
  ecal/core/src/readwrite/ecal_writer_base.h
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.h
  ecal/core/src/readwrite/tcp/ecal_writer_tcp.cpp
  ecal/core/src/readwrite/tcp/ecal_writer_tcp.h
  ecal/core/src/readwrite/udp/ecal_writer_udp_mc.cpp
  ecal/core/src/readwrite/udp/ecal_writer_udp_mc.h
Labels: cherry-pick-to-NONE

#1575 [Core Tests] Added missing include
  ecal/tests/cpp/util_test/src/util_gettopics.cpp
Labels: cherry-pick-to-NONE

#1526 [Python] Added BinarySubscriber and BinaryPublisher with examples
  lang/python/core/ecal/core/publisher.py
  lang/python/core/ecal/core/subscriber.py
  samples/CMakeLists.txt
  samples/python/pubsub/binary/binary_rec/CMakeLists.txt
  samples/python/pubsub/binary/binary_rec/binary_rec.py
  samples/python/pubsub/binary/binary_rec/binary_rec.pyproj
  samples/python/pubsub/binary/binary_rec_cb/CMakeLists.txt
  samples/python/pubsub/binary/binary_rec_cb/binary_rec_cb.py
  samples/python/pubsub/binary/binary_rec_cb/binary_rec_cb.pyproj
  samples/python/pubsub/binary/binary_snd/CMakeLists.txt
  samples/python/pubsub/binary/binary_snd/binary_snd.py
  samples/python/pubsub/binary/binary_snd/binary_snd.pyproj
Labels: cherry-pick-to-NONE
