Repository eclipse-ecal/ecal, pull requests merged in 2024-10, with the labels that each got.

#1750 [python] Fix iterating over measurement which was broken by fe84826
  lang/python/ecalhdf5/ecal/measurement/measurement.py
Labels: bug, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1754 Fix memory leaks in Python wrapper by adding missing Py_DECREF.
  lang/python/core/src/ecal_wrap.cxx
  lang/python/ecalhdf5/src/ecalhdf5_wrap.cxx
Labels: bug, cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1760 [python] Call_method in service now allows threads.
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#1764 [core] fix bug that processes will not be "unregistered" correctly.
  ecal/core/src/registration/ecal_process_registration.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/tests/cpp/serialization_test/src/registration_generate.cpp
Labels: bug, cherry-pick-to-NONE

#1766 [core] improved nanopb generation
  build_win/nanopb/compile-nanopb.bat
  build_win/nanopb/compile-nanopb.py
  ecal/core/CMakeLists.txt
  ecal/core/src/serialization/ecal_serialize_common.cpp
  ecal/core/src/serialization/ecal_serialize_logging.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_payload.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_serialize_service.cpp
  ecal/core/src/serialization/nanopb/ecal/core/pb/ecal.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/ecal.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/host.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/host.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/layer.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/layer.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/logging.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/logging.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/monitoring.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/monitoring.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/process.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/process.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/service.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/service.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.h
  ecal/core/src/serialization/nanopb/pb.h
  ecal/core/src/serialization/nanopb/pb_common.c
  ecal/core/src/serialization/nanopb/pb_common.h
  ecal/core/src/serialization/nanopb/pb_decode.c
  ecal/core/src/serialization/nanopb/pb_decode.h
  ecal/core/src/serialization/nanopb/pb_encode.c
  ecal/core/src/serialization/nanopb/pb_encode.h
  ecal/tests/cpp/serialization_test/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1771 [config] Hotfix: pragma once removal in source files
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
  ecal/core/src/pubsub/config/builder/writer_attribute_builder.cpp
  ecal/core/src/readwrite/config/builder/shm_attribute_builder.cpp
  ecal/core/src/readwrite/config/builder/tcp_attribute_builder.cpp
  ecal/core/src/readwrite/config/builder/udp_attribute_builder.cpp
  ecal/core/src/readwrite/tcp/config/builder/data_reader_tcp_attribute_builder.cpp
  ecal/core/src/readwrite/udp/config/builder/udp_attribute_builder.cpp
Labels: cherry-pick-to-NONE

#1774 [Doc] Added default python version for Ubuntu 24.04
  doc/extensions/generate_download_tables.py
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13
