Repository eclipse-ecal/ecal, pull requests merged in 2025-03, with the labels that each got.

#2046 Feature/msg api improvements
  CMakeLists.txt
  app/mon/mon_cli/src/ecal_mon_cli.cpp
  app/mon/mon_plugins/string_reflection/src/metadata.json
  app/mon/mon_plugins/string_reflection/src/plugin_widget.h
  app/mon/mon_tui/src/tui/viewmodel/message_visualization/string.hpp
  serialization/capnproto/CMakeLists.txt
  serialization/capnproto/capnproto/CMakeLists.txt
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/dynamic.h
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/helper.h
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/publisher.h
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/serializer.h
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/subscriber.h
  serialization/capnproto/samples/pubsub/addressbook_snd/src/addressbook_snd.cpp
  serialization/capnproto/tests/CMakeLists.txt
  serialization/capnproto/tests/addressbook.capnp
  serialization/capnproto/tests/serialization_test.cpp
  serialization/common/common/CMakeLists.txt
  serialization/common/common/include/ecal/msg/exception.h
  serialization/common/common/include/ecal/msg/message.h
  serialization/common/common/include/ecal/msg/publisher.h
  serialization/common/common/include/ecal/msg/subscriber.h
  serialization/common/core/include/ecal/msg/dynamic.h
  serialization/common/core/include/ecal/msg/publisher.h
  serialization/common/core/include/ecal/msg/subscriber.h
  serialization/flatbuffers/flatbuffers/include/ecal/msg/flatbuffers/publisher.h
  serialization/flatbuffers/flatbuffers/include/ecal/msg/flatbuffers/serializer.h
  serialization/flatbuffers/flatbuffers/include/ecal/msg/flatbuffers/subscriber.h
  serialization/flatbuffers/samples/pubsub/monster_rec/monster_rec.cpp
  serialization/flatbuffers/samples/pubsub/monster_snd/monster_snd.cpp
  serialization/protobuf/CMakeLists.txt
  serialization/protobuf/protobuf/CMakeLists.txt
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/dynamic_json_subscriber.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/dynamic_publisher.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/dynamic_subscriber.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/publisher.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/serializer.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/subscriber.h
  serialization/protobuf/samples/pubsub/proto_dyn_snd/src/proto_dyn_snd.cpp
  serialization/protobuf/samples/pubsub/proto_dyn_snd/src/protobuf/animal.proto
  serialization/protobuf/samples/pubsub/proto_dyn_snd/src/protobuf/house.proto
  serialization/protobuf/tests/pubsub_proto_test/src/proto_subscriber_test.cpp
  serialization/string/samples/pubsub/minimal_rec/src/minimal_rec.cpp
  serialization/string/samples/pubsub/minimal_snd/src/minimal_snd.cpp
  serialization/string/string/include/ecal/msg/string/publisher.h
  serialization/string/string/include/ecal/msg/string/serializer.h
  serialization/string/string/include/ecal/msg/string/subscriber.h
Labels: cherry-pick-to-NONE

#2054 [config] Feature/remove yaml installation
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  cpack/innosetup/ecal_setup.iss.in
  doc/rst/configuration/options.rst
  ecal/core/cfg/CMakeLists.txt
  ecal/core/cfg/generate_configuration_yaml.cpp
  ecal/core/src/config/configuration.cpp
  ecal/core/src/config/ecal_path_processing.cpp
  ecal/core/src/config/ecal_path_processing.h
  ecal/core/src/ecal_def.h
  ecal/tests/cpp/config_test/CMakeLists.txt
  ecal/tests/cpp/config_test/src/path_processing_test.cpp
  lib/ecal_utils/src/filesystem.cpp
Labels: cherry-pick-to-NONE

#2055 [core] Removed reference counting for eCAL::Initialize()
  app/play/play_cli/src/ecal_play_cli.cpp
  app/play/play_core/src/ecal_play.cpp
  app/play/play_gui/src/main.cpp
  app/rec/rec_client_cli/src/ecal_rec_cli.cpp
  app/rec/rec_client_core/src/ecal_rec.cpp
  app/rec/rec_gui/src/main.cpp
  app/rec/rec_server_core/src/rec_server_impl.cpp
  app/sys/sys_cli/src/ecalsys_cli.cpp
  app/sys/sys_core/src/ecal_sys.cpp
  ecal/core/src/ecal.cpp
  ecal/core/src/ecal_global_accessors.cpp
  ecal/core/src/ecal_global_accessors.h
  ecal/tests/cpp/core_test/src/core_test.cpp
  lang/c/tests/core_test/src/core_test.cpp
Labels: cherry-pick-to-NONE

#2059 [config] Logging renamed filter_log to level in logging configuration.
  ecal/core/include/ecal/config/logging.h
  ecal/core/src/config/builder/logging_attribute_builder.cpp
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/logging/config/attributes/ecal_log_provider_attributes.h
  ecal/core/src/logging/ecal_log_provider.cpp
  ecal/tests/cpp/config_test/src/config_test.cpp
  ecal/tests/cpp/logging_test/src/logging_test.cpp
Labels: cherry-pick-to-NONE

#2058 [config] Improved network configuration options
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/config/registration.h
  ecal/core/include/ecal/config/transport_layer.h
  ecal/core/include/ecal/types/custom_data_types.h
  ecal/core/src/config/builder/logging_attribute_builder.cpp
  ecal/core/src/config/builder/logging_attribute_builder.h
  ecal/core/src/config/builder/registration_attribute_builder.cpp
  ecal/core/src/config/builder/registration_attribute_builder.h
  ecal/core/src/config/configuration_reader.cpp
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/configuration_to_yaml.h
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/io/udp/ecal_udp_configurations.cpp
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.h
  ecal/core/src/pubsub/config/builder/writer_attribute_builder.cpp
  ecal/core/src/pubsub/config/builder/writer_attribute_builder.h
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/readwrite/config/attributes/reader_attributes.h
  ecal/core/src/readwrite/config/attributes/writer_attributes.h
  ecal/core/src/readwrite/config/builder/udp_attribute_builder.cpp
  ecal/core/src/registration/config/attributes/registration_attributes.h
  ecal/core/src/registration/config/builder/udp_shm_attribute_builder.cpp
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/registration/ecal_registration_receiver.cpp
  ecal/core/src/registration/udp/config/attributes/registration_receiver_udp_attributes.h
  ecal/core/src/v5/pubsub/ecal_publisher.cpp
  ecal/core/src/v5/pubsub/ecal_subscriber.cpp
  ecal/samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
  ecal/samples/cpp/misc/config/src/config_sample.cpp
  ecal/tests/cpp/config_test/src/ini_file.h
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
Labels: cherry-pick-to-NONE

#2061 [Mon] eCAL Mon can now open the yaml as root on Ubuntu
  app/mon/mon_gui/src/widgets/system_information_widget/system_information_widget.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2063 [Tests] Increased timeouts of rec rpc test
  app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13

#2062 [config] Test for yaml read and write
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/tests/cpp/config_test/CMakeLists.txt
  ecal/tests/cpp/config_test/src/config_test.cpp
  ecal/tests/cpp/config_test/src/yaml_processing_test.cpp
Labels: cherry-pick-to-NONE

#2067 [Rec] Added mDNS support for FTP Uploads
  app/rec/rec_client_core/src/job/ftp_upload_thread.cpp
  app/rec/rec_client_core/src/job/ftp_upload_thread.h
  app/rec/rec_client_core/src/job/record_job.cpp
Labels: cherry-pick-to-NONE

#2070 [Tests] Increased timeouts of rec rpc test
  app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2069 [Tests] Increased timeouts of rec rpc test
  app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2068 [config] Revert install sysconfdir handling
  .github/workflows/build-ubuntu.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  ecal/core/src/ecal_def.h
Labels: cherry-pick-to-NONE

#2072 [core] Provide serializer.h for installation
  README.md
  doc/rst/configuration/src/publisher_config/main.cpp
  doc/rst/getting_started/src/hello_world/hello_world_rec/main.cpp
  doc/rst/getting_started/src/hello_world/hello_world_snd/main.cpp
  serialization/flatbuffers/flatbuffers/CMakeLists.txt
  serialization/protobuf/protobuf/CMakeLists.txt
  serialization/string/string/CMakeLists.txt
Labels: cherry-pick-to-NONE

#2073 [core] Removed dead API function Process::GetTaskParameter() and changed argument type of Process::SetState() to std::string
  ecal/core/include/ecal/process.h
  ecal/core/src/ecal_global_accessors.cpp
  ecal/core/src/ecal_global_accessors.h
  ecal/core/src/ecal_process.cpp
  lang/c/core/include/ecal_c/process.h
  lang/c/core/src/process.cpp
Labels: cherry-pick-to-NONE

#2071 [core] Adapted API in order to return const references if possible
  ecal/core/include/ecal/config.h
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/core.h
  ecal/core/include/ecal/process.h
  ecal/core/include/ecal/pubsub/publisher.h
  ecal/core/include/ecal/pubsub/subscriber.h
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/client_instance.h
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/time.h
  ecal/core/include/ecal/types/custom_data_types.h
  ecal/core/src/config/configuration.cpp
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/ecal.cpp
  ecal/core/src/ecal_process.cpp
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/time/ecal_time.cpp
  ecal/core/src/time/ecal_timegate.cpp
  ecal/core/src/time/ecal_timegate.h
  ecal/core/src/types/ecal_custom_data_types.cpp
  ecal/core/src/v5/pubsub/ecal_subscriber.cpp
  serialization/common/common/include/ecal/msg/publisher.h
  serialization/common/common/include/ecal/msg/subscriber.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client_instance.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client_untyped_instance.h
Labels: cherry-pick-to-NONE

#2077 [msg] Avoid deadlocking with CMessageSubscriber
  app/mon/mon_plugins/capnproto_reflection/src/plugin_widget.cpp
  app/mon/mon_plugins/protobuf_reflection/src/plugin_widget.cpp
  app/mon/mon_plugins/signals_plotting/src/plugin_widget.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  serialization/common/common/include/ecal/msg/subscriber.h
  serialization/protobuf/tests/pubsub_proto_test/src/proto_subscriber_test.cpp
Labels: cherry-pick-to-NONE

#2076 [doc] Collect doc samples according to "repo standard" and enable build
  .github/workflows/documentation.yml
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/rst/configuration/runtime_configuration.rst
  doc/rst/configuration/src/hello_config/main.cpp
  doc/rst/getting_started/hello_world.rst
  doc/rst/getting_started/hello_world_proto.rst
  doc/rst/getting_started/hello_world_python.rst
  doc/rst/getting_started/hello_world_python_proto.rst
  doc/samples/CMakeLists.txt
  doc/samples/cpp/configuration/hello_config/CMakeLists.txt
  doc/samples/cpp/configuration/hello_config/main.cpp
  doc/samples/cpp/configuration/publisher_config/CMakeLists.txt
  doc/samples/cpp/configuration/publisher_config/main.cpp
  doc/samples/cpp/protobuf/hello_world_rec/CMakeLists.txt
  doc/samples/cpp/protobuf/hello_world_rec/main.cpp
  doc/samples/cpp/protobuf/hello_world_snd/CMakeLists.txt
  doc/samples/cpp/protobuf/hello_world_snd/main.cpp
  doc/samples/cpp/protobuf/proto_messages/hello_world.proto
  doc/samples/cpp/string/hello_world_rec/CMakeLists.txt
  doc/samples/cpp/string/hello_world_rec/main.cpp
  doc/samples/cpp/string/hello_world_snd/CMakeLists.txt
  doc/samples/cpp/string/hello_world_snd/main.cpp
  doc/samples/python/protobuf/hello_world_rec.py
  doc/samples/python/protobuf/hello_world_snd.py
  doc/samples/python/protobuf/proto_messages/hello_world.proto
  doc/samples/python/string/hello_world_rec.py
  doc/samples/python/string/hello_world_snd.py
Labels: cherry-pick-to-NONE

#2080 [core] Make deserializer member of subscriber
  serialization/common/common/include/ecal/msg/subscriber.h
Labels: cherry-pick-to-NONE

#2082 [GH Action] Wheels are now built for all pushes and pull requests
  .github/workflows/build_wheels.yml
Labels: Auto Approve, cherry-pick-to-NONE

#2084 [lang] Cleanup and additional documentation of C API
  lang/c/core/CMakeLists.txt
  lang/c/core/include/ecal_c/ecal.h
  lang/c/core/include/ecal_c/init.h
  lang/c/core/include/ecal_c/log_level.h
  lang/c/core/include/ecal_c/process_severity.h
  lang/c/core/include/ecal_c/pubsub/payload_writer.h
  lang/c/core/include/ecal_c/pubsub/subscriber.h
  lang/c/core/include/ecal_c/pubsub/types.h
  lang/c/core/include/ecal_c/service/client.h
  lang/c/core/include/ecal_c/service/client_instance.h
  lang/c/core/include/ecal_c/service/server.h
  lang/c/core/include/ecal_c/service/types.h
  lang/c/core/include/ecal_c/timer.h
  lang/c/core/include/ecal_c/types/monitoring.h
  lang/c/core/src/client.cpp
  lang/c/core/src/client_instance.cpp
  lang/c/core/src/client_instance.h
  lang/c/core/src/common.cpp
  lang/c/core/src/publisher.cpp
  lang/c/core/src/server.cpp
  lang/c/core/src/subscriber.cpp
  lang/c/core/src/time.cpp
  lang/c/core/src/timer.cpp
Labels: cherry-pick-to-NONE

#2085 [docu] Latest configuration adaptions
  doc/CMakeLists.txt
  doc/include.txt
  doc/rst/advanced/ecal_in_docker.rst
  doc/rst/configuration.rst
  doc/rst/configuration/cloud.rst
  doc/rst/configuration/local.rst
  doc/rst/configuration/network.rst
  doc/rst/configuration/npcap.rst
  doc/rst/configuration/options.rst
  doc/rst/configuration/runtime_configuration.rst
  doc/rst/getting_started/hello_world.rst
  doc/rst/getting_started/hello_world_proto.rst
  doc/rst/getting_started/hello_world_python_proto.rst
  doc/rst/getting_started/introduction.rst
  doc/rst/getting_started/monitor.rst
  doc/rst/getting_started/network.rst
  doc/rst/getting_started/services.rst
  doc/rst/getting_started/setup.rst
  doc/rst/getting_started/sys.rst
  doc/rst/include.txt
  doc/rst/index.rst
  doc/samples/python/protobuf/hello_world_rec.py
  doc/samples/python/protobuf/hello_world_snd.py
  doc/samples/python/string/hello_world_rec.py
  doc/samples/python/string/hello_world_snd.py
  ecal/core/cfg/CMakeLists.txt
Labels: cherry-pick-to-NONE

#2090 [lang] Added full logging and monitoring interface to C API
  lang/c/core/include/ecal_c/log.h
  lang/c/core/include/ecal_c/monitoring.h
  lang/c/core/include/ecal_c/types/logging.h
  lang/c/core/include/ecal_c/types/monitoring.h
  lang/c/core/src/log.cpp
  lang/c/core/src/monitoring.cpp
Labels: cherry-pick-to-NONE

#2092 [bugfix] Allow to store empty strings for DataTypeInformation in measurement
  contrib/ecalhdf5/src/hdf5_helper.cpp
  contrib/ecalhdf5/src/hdf5_helper.h
  tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Labels: cherry-pick-to-NONE

#2094 [cmake] Excluded v5 headers from installation and removed all v5 tests and samples
  ecal/core/CMakeLists.txt
  ecal/samples/CMakeLists.txt
  ecal/samples/cpp/pubsub/binary/ping/CMakeLists.txt
  ecal/samples/cpp/pubsub/binary/ping/src/ping.cpp
  ecal/samples/cpp/pubsub/binary/pong/CMakeLists.txt
  ecal/samples/cpp/pubsub/binary/pong/src/pong.cpp
  ecal/tests/CMakeLists.txt
  ecal/tests/cpp/clientserver_v5_test/CMakeLists.txt
  ecal/tests/cpp/clientserver_v5_test/src/atomic_signalable.h
  ecal/tests/cpp/clientserver_v5_test/src/clientserver_test.cpp
  ecal/tests/cpp/pubsub_v5_test/CMakeLists.txt
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_callback_topicid.cpp
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_connection_test.cpp
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_receive_test.cpp
  lang/c/core/src/publisher.cpp
Labels: cherry-pick-to-NONE
