Repository eclipse-ecal/ecal, pull requests merged in 2025-02, with the labels that each got.

#1995 [doc] blanks and python build
  doc/rst/development/building_ecal_from_source.rst
  doc/rst/development/ecal_cmake_options.rst
Labels: cherry-pick-to-NONE

#1993 [build] ECAL_BUILD_APP_SDK build options
  .github/workflows/build-windows.yml
  CMakeLists.txt
Labels: cherry-pick-to-NONE

#1992 [mma] Hotfix: mma kills all processs
  contrib/mma/src/zombie_instance_killer.cpp
Labels: cherry-pick-to-NONE

#1996 fix[cmake]: Remove thirdparty build options from presets
  CMakePresets.json
Labels: cherry-pick-to-NONE

#1991 [core] remove function declaration without implementation
  ecal/core/include/ecal/config.h
Labels: cherry-pick-to-NONE

#1892 [cmake] Use GNU install dirs variables instead of hardcoded value
  CMakeLists.txt
  app/app_pb/CMakeLists.txt
  app/apps/CMakeLists.txt
  app/mon/mon_plugin_lib/CMakeLists.txt
  app/rec/rec_addon_core/CMakeLists.txt
  cmake/helper_functions/ecal_install_functions.cmake
  contrib/ecalhdf5/CMakeLists.txt
  contrib/ecaltime/ecaltime_pb/CMakeLists.txt
  contrib/measurement/base/CMakeLists.txt
  contrib/measurement/hdf5/CMakeLists.txt
  ecal/core/CMakeLists.txt
  ecal/core_pb/CMakeLists.txt
  lang/c/core/CMakeLists.txt
  lang/csharp/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core.Test/CMakeLists.txt
  lang/csharp/Continental.eCAL.Core/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf.Test/CMakeLists.txt
  lang/csharp/Continental.eCAL.Protobuf/CMakeLists.txt
  thirdparty/asio/build-asio.cmake
  thirdparty/cmakefunctions/cmake_functions/CMakeLists.txt
  thirdparty/hdf5/build-hdf5.cmake
Labels: cherry-pick-to-NONE

#1997 [cmake]: Disable unwanted curl options and put missed targets in correct IDE folder
  thirdparty/curl/build-curl.cmake
  thirdparty/yaml-cpp/build-yaml-cpp.cmake
Labels: cherry-pick-to-NONE

#2008 [GH Action] Added arm64 gh actions for ubuntu
  .github/workflows/build-ubuntu.yml
Labels: Auto Approve, cherry-pick-to-NONE

#2012 [config] Remove ecal config initializer
  ecal/core/src/config/ecal_config_initializer.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2013 [benchmarks] Move service benchmarks to appropriate directory
  ecal/samples/CMakeLists.txt
  ecal/samples/cpp/benchmarks/latency_client/CMakeLists.txt
  ecal/samples/cpp/benchmarks/latency_client/src/latency_client.cpp
  ecal/samples/cpp/benchmarks/latency_server/CMakeLists.txt
  ecal/samples/cpp/benchmarks/latency_server/src/latency_server.cpp
Labels: cherry-pick-to-NONE

#2015 [python] Removed buggy initialize() signature
  lang/python/core/ecal/core/core.py
Labels: cherry-pick-to-NONE

#2018 [build] Remove some build warnings
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/service/test/src/ecal_tcp_service_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2019 [Doc] Documentation now links to the release page
  .gitignore
  NOTICE.md
  doc/extensions/empy_helpers/__init__.py
  doc/extensions/generate_download_tables.py
  doc/extensions/generate_release_documentation.py
  doc/extensions/resource/download_archive.rst.em
  doc/extensions/resource/download_archive_page.rst.em
  doc/extensions/resource/download_table.html.em
  doc/extensions/resource/main_page_download_section.rst.em
  doc/extensions/resource/ppa_instructions_multiversion_tabs.rst.jinja
  doc/extensions/resource/ppa_instructions_singleversion.rst.jinja
  doc/extensions/resource/ppa_tabs.rst.em
  doc/extensions/resource/release_page_index.rst.jinja
  doc/release_page/conf.py
  doc/release_page/generate_release_documentation/__init__.py
  doc/release_page/resource/release_page.rst.jinja
  doc/release_page/resource/release_page_index.rst.jinja
  doc/requirements.txt
  doc/rst/conf.py
  doc/rst/getting_started/setup.rst
  doc/rst/index.rst
  doc/rst/license/thirdparty_licenses.rst
Labels: Auto Approve, cherry-pick-to-NONE

#2020 [Doc] Fixed parsing of ecal_doc_version number
  doc/rst/conf.py
Labels: Auto Approve, cherry-pick-to-NONE

#2021 [Doc] Documentation now links to the release page (5.13)
  .gitignore
  doc/extensions/empy_helpers/__init__.py
  doc/extensions/generate_download_tables.py
  doc/extensions/generate_release_documentation.py
  doc/extensions/resource/download_archive.rst.em
  doc/extensions/resource/download_archive_page.rst.em
  doc/extensions/resource/download_table.html.em
  doc/extensions/resource/main_page_download_section.rst.em
  doc/extensions/resource/ppa_instructions_multiversion_tabs.rst.jinja
  doc/extensions/resource/ppa_instructions_singleversion.rst.jinja
  doc/extensions/resource/ppa_tabs.rst.em
  doc/extensions/resource/release_page.rst.jinja
  doc/extensions/resource/release_page_index.rst.jinja
  doc/requirements.txt
  doc/rst/conf.py
  doc/rst/getting_started/setup.rst
  doc/rst/index.rst
Labels: Auto Approve

#2022 [Doc] Fixed compile issue when compiling for the latest stable version
  doc/rst/conf.py
Labels: Auto Approve, cherry-pick-to-support/v5.13

#2024 [Doc] Documentation now links to the release page
  .gitignore
  doc/extensions/empy_helpers/__init__.py
  doc/extensions/generate_download_tables.py
  doc/extensions/generate_release_documentation.py
  doc/extensions/resource/download_archive.rst.em
  doc/extensions/resource/download_archive_page.rst.em
  doc/extensions/resource/download_table.html.em
  doc/extensions/resource/main_page_download_section.rst.em
  doc/extensions/resource/ppa_instructions_multiversion_tabs.rst.jinja
  doc/extensions/resource/ppa_instructions_singleversion.rst.jinja
  doc/extensions/resource/ppa_tabs.rst.em
  doc/extensions/resource/release_page.rst.jinja
  doc/extensions/resource/release_page_index.rst.jinja
  doc/requirements.txt
  doc/rst/conf.py
  doc/rst/getting_started/setup.rst
  doc/rst/index.rst
Labels: Auto Approve

#2017 [logging] eCALLogDir returns now subfolder "logs" in special cases
  ecal/core/include/ecal/util.h
  ecal/core/src/config/ecal_path_processing.cpp
  ecal/core/src/config/ecal_path_processing.h
  ecal/tests/cpp/config_test/src/path_processing_test.cpp
Labels: cherry-pick-to-NONE

#2025 [python] Removed dead function wrapper
  lang/python/core/ecal/core/core.py
Labels: cherry-pick-to-NONE

#2027 [core] Fixed acknowledge bug for multiple processes
  ecal/core/src/io/shm/ecal_memfile_sync.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
Labels: cherry-pick-to-NONE

#2031 [cmake] Remove tests from debian installer
  cpack/cpack_variables.cmake
Labels: cherry-pick-to-NONE

#2033 [core] Added missing lvalue reference in CSyncMemoryFile::Disconnect()
  ecal/core/src/io/shm/ecal_memfile_sync.cpp
Labels: bug, cherry-pick-to-NONE

#2034 [cmake] Require CXX14 for core compilation.
  ecal/core/CMakeLists.txt
Labels: cherry-pick-to-NONE

#2036 [app] Path separator for log path.
  app/play/play_core/include/ecal_play_logger.h
  app/rec/rec_client_core/include/rec_client_core/ecal_rec_logger.h
  app/sys/sys_client_core/include/sys_client_core/ecal_sys_client_logger.h
  app/sys/sys_core/CMakeLists.txt
  app/sys/sys_core/include/ecalsys/ecal_sys_logger.h
Labels: cherry-pick-to-NONE

#2039 [repo] Move mma to app folder.
  CMakeLists.txt
  app/mma/CMakeLists.txt
  app/mma/README.md
  app/mma/bat/perfmon_counters_rebuild.bat
  app/mma/bat/start_mma_hidden.bat
  app/mma/include/interruptable_timer.h
  app/mma/include/linux/mma_linux.h
  app/mma/include/linux/pipe_refresher.h
  app/mma/include/linux/ressource.h
  app/mma/include/logger.h
  app/mma/include/mma.h
  app/mma/include/mma_defs.h
  app/mma/include/mma_impl.h
  app/mma/include/query_manager.h
  app/mma/include/windows/disk.h
  app/mma/include/windows/memory.h
  app/mma/include/windows/mma_windows.h
  app/mma/include/windows/network.h
  app/mma/include/windows/process.h
  app/mma/include/windows/processes.h
  app/mma/include/windows/processor.h
  app/mma/include/windows/ressource.h
  app/mma/include/zombie_instance_killer.h
  app/mma/src/linux/mma_linux.cpp
  app/mma/src/linux/pipe_refresher.cpp
  app/mma/src/logger.cpp
  app/mma/src/mma.cpp
  app/mma/src/mma.rc
  app/mma/src/mma_application.cpp
  app/mma/src/query_manager.cpp
  app/mma/src/windows/disk.cpp
  app/mma/src/windows/memory.cpp
  app/mma/src/windows/mma_windows.cpp
  app/mma/src/windows/network.cpp
  app/mma/src/windows/process.cpp
  app/mma/src/windows/processes.cpp
  app/mma/src/windows/processor.cpp
  app/mma/src/windows/ressource.cpp
  app/mma/src/zombie_instance_killer.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#2038 [cleanup] Remove cross build example, as it has not actively been used.
  tests/contrib/cross/.dockerignore
  tests/contrib/cross/.gitignore
  tests/contrib/cross/Makefile
  tests/contrib/cross/README.md
  tests/contrib/cross/host/Dockerfile
  tests/contrib/cross/target/ubuntu18.Dockerfile
  tests/contrib/cross/toolchain-arm64.cmake
Labels: cherry-pick-to-NONE

#2049 [readme.md] Fixed link to downloads
  README.md
Labels: Auto Approve, cherry-pick-to-support/v5.13
