Repository eclipse-ecal/ecal, pull requests merged in 2025-08, with the labels that each got.

#2278 [python] fix memory leaks by adding missing Py_DECREF.
  lang/python/core/src/ecal_wrap.cxx
Labels: Auto Approve, cherry-pick-to-NONE

#2307 [Doc] Fixed release page (cpu arch and pypy bindings)
  doc/extensions/generate_release_documentation.py
  doc/extensions/resource/release_page.rst.jinja
Labels: Auto Approve, cherry-pick-to-NONE

#2301 [build] Static app helper libraries
  app/mon/mon_plugins/monitor_tree_view/CMakeLists.txt
  app/play/play_core/CMakeLists.txt
  app/rec/rec_client_core/CMakeLists.txt
  app/rec/rec_server_core/CMakeLists.txt
  app/sys/sys_client_core/CMakeLists.txt
  app/sys/sys_core/CMakeLists.txt
Labels: cherry-pick-to-support/v6.0

#2300 [build] Avoid mirror_server name clash with HDF5
  ecal/samples/cpp/services/mirror_client/CMakeLists.txt
  ecal/samples/cpp/services/mirror_server/CMakeLists.txt
Labels: cherry-pick-to-support/v6.0

#2316 fix: Assign supporting desktop files to the app component
  app/play/play_gui/CMakeLists.txt
  app/rec/rec_gui/CMakeLists.txt
  app/sys/sys_gui/CMakeLists.txt
  cmake/helper_functions/ecal_install_functions.cmake
Labels: Auto Approve

#2318 Added a python-specific readme.md that is also used by the python wheels.
  lang/python/README.md
  pyproject.toml
Labels: cherry-pick-to-support/v6.0

#2283 Add GitHub Action to Trigger Test Suite (ecal-test-suite)
  .github/workflows/test-suite-trigger.yml
Labels: cherry-pick-to-NONE

#2323 [CMake / Qt] Windeployqt calls are now waiting for each other
  app/mon/mon_gui/CMakeLists.txt
  app/play/play_gui/CMakeLists.txt
  app/rec/rec_gui/CMakeLists.txt
  app/sys/sys_gui/CMakeLists.txt
  app/util/launcher/CMakeLists.txt
  samples/cpp/services/ecalplayer_gui_client/CMakeLists.txt
  samples/cpp/services/rec_client_service_gui/CMakeLists.txt
  samples/cpp/services/rec_server_service_gui/CMakeLists.txt
  thirdparty/cmakefunctions/cmake_functions/cmake_functions.cmake
  thirdparty/cmakefunctions/cmake_functions/qt/exclusive_command.cmake
  thirdparty/cmakefunctions/cmake_functions/qt/exclusive_command.ps1
  thirdparty/qwt/CMakeLists.txt
Labels: cherry-pick-to-support/v6.0

#2329 [Doc] Fixed dependency versions that cannot be updated safely without interaction
  doc/pyproject.toml
Labels: cherry-pick-to-support/v6.0

#2334 Downgrade protobuf on macos.
  .github/workflows/build-macos.yml
Labels: cherry-pick-to-support/v6.0

#2349 [License doc] Added generation script for NOTICE.md
  LICENSES/ecal_license_collector/jinja2/notice.md.jinja
  LICENSES/ecal_license_collector/update_licenses_information.py
Labels: Auto Approve, cherry-pick-to-support/v6.0
