Repository eclipse-ecal/ecal, pull requests merged in 2025-01, with the labels that each got.

#1873 [core] Removed custom user cli arguments from configuration object
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/config/user_arguments.h
  ecal/core/src/ecal.cpp
Labels: cherry-pick-to-NONE

#1872 [core] Change entity_id type from std::string to uint64_t
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/include/ecal/ecal_types.h
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.h
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/readwrite/config/builder/tcp_attribute_builder.cpp
  ecal/core/src/readwrite/config/builder/tcp_attribute_builder.h
  ecal/core/src/readwrite/config/builder/udp_attribute_builder.cpp
  ecal/core/src/readwrite/config/builder/udp_attribute_builder.h
  ecal/core/src/readwrite/ecal_reader_layer.h
  ecal/core/src/readwrite/ecal_writer_base.h
  ecal/core/src/readwrite/shm/ecal_reader_shm.h
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
  ecal/core/src/readwrite/shm/ecal_writer_shm.h
  ecal/core/src/readwrite/tcp/config/attributes/data_writer_tcp_attributes.h
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp
  ecal/core/src/readwrite/tcp/ecal_reader_tcp.h
  ecal/core/src/readwrite/udp/config/attributes/writer_udp_attributes.h
  ecal/core/src/readwrite/udp/ecal_reader_udp.cpp
  ecal/core/src/readwrite/udp/ecal_reader_udp.h
  ecal/core/src/registration/ecal_process_registration.cpp
  ecal/core/src/serialization/ecal_serialize_common.cpp
  ecal/core/src/serialization/ecal_serialize_common.h
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_payload.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_struct_sample_payload.h
  ecal/core/src/serialization/ecal_struct_sample_registration.h
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/service/test/src/ecal_tcp_service_test.cpp
  ecal/tests/cpp/descgate_test/src/descgate_getentities.cpp
  ecal/tests/cpp/registration_test/src/registration_timout_provider_test.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  ecal/tests/cpp/serialization_test/src/payload_generate.cpp
  ecal/tests/cpp/serialization_test/src/registration_generate.cpp
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1875 [core] get service id implementation
  ecal/core/include/ecal/ecal_client.h
  ecal/core/include/ecal/ecal_registration.h
  ecal/core/include/ecal/ecal_server.h
  ecal/core/include/ecal/ecal_types.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
Labels: cherry-pick-to-NONE

#1882 [config] Call InitFromConfig() when initialize is not called with config parameter
  ecal/core/src/ecal.cpp
Labels: cherry-pick-to-NONE

#1881 [core] new service response struct/callback type using SServiceMethodID
  ecal/core/include/ecal/ecal_client.h
  ecal/core/include/ecal/ecal_client_instance.h
  ecal/core/include/ecal/ecal_service_info.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/service/ecal_service_client_v5_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1883 Use uint64_t for topic id in hdf5
  contrib/ecalhdf5/src/hdf5_helper.cpp
  contrib/ecalhdf5/src/hdf5_helper.h
  contrib/measurement/base/include/ecal/measurement/base/types.h
  tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Labels: cherry-pick-to-NONE

#1878 [mon_gui] Logging enable, crash fix
  app/mon/mon_gui/src/ecalmon.cpp
  app/mon/mon_gui/src/widgets/models/log_model.cpp
  ecal/core/src/logging/ecal_log.cpp
  ecal/core/src/logging/ecal_log_receiver.cpp
  ecal/core/src/logging/ecal_log_receiver.h
Labels: cherry-pick-to-NONE

#1876 [core] service client use datainfo
  ecal/core/include/ecal/ecal_server.h
  ecal/core/include/ecal/ecal_service_info.h
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_service_server_v5_impl.cpp
  ecal/samples/cpp/services/latency_server/src/latency_server.cpp
  ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1885 [core] Completely remove the ability not to transmit type and descrip…
  ecal/core/include/ecal/config/publisher.h
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
  ecal/core/src/pubsub/config/builder/reader_attribute_builder.h
  ecal/core/src/pubsub/config/builder/writer_attribute_builder.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_v5.cpp
  ecal/core/src/readwrite/config/attributes/writer_attributes.h
Labels: cherry-pick-to-NONE

#1886 [core] remove unused internal header file.
  ecal/core/CMakeLists.txt
  ecal/core/src/ecal_def_ini.h
Labels: cherry-pick-to-NONE

#1888 [config] Hotfix/mon apps initialization
  app/mon/mon_cli/src/ecal_mon_cli.cpp
  app/mon/mon_gui/src/ecalmon.cpp
  app/mon/mon_tui/src/main.cpp
Labels: cherry-pick-to-NONE

#1887 [core] service client use datainfo (post fixes)
  ecal/core/include/ecal/ecal_service_info.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_v5_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_v5_impl.cpp
  ecal/samples/cpp/services/latency_server/src/latency_server.cpp
  ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
Labels: cherry-pick-to-NONE

#1893 [core] split ecal_callback.h into v5 and v6
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/include/ecal/ecal_callback_v5.h
  ecal/core/include/ecal/ecal_client_v5.h
  ecal/core/include/ecal/ecal_publisher_v5.h
  ecal/core/include/ecal/ecal_server_v5.h
  ecal/core/include/ecal/ecal_subscriber_v5.h
  ecal/core/src/cimpl/ecal_client_cimpl.cpp
  ecal/core/src/cimpl/ecal_publisher_cimpl.cpp
  ecal/core/src/cimpl/ecal_server_cimpl.cpp
  ecal/core/src/cimpl/ecal_subscriber_cimpl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_v5_impl.cpp
  ecal/core/src/service/ecal_service_client_v5_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_service_server_v5_impl.cpp
  ecal/core/src/service/ecal_service_server_v5_impl.h
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/clientserver_v5_test/src/clientserver_test.cpp
  lang/python/core/src/ecal_clang.cpp
  serialization/protobuf/samples/pubsub/person_events_rec/src/person_events_rec.cpp
  serialization/protobuf/samples/pubsub/person_events_snd/src/person_events_snd.cpp
  serialization/protobuf/samples/services/math_client/src/math_client.cpp
  serialization/protobuf/samples/services/math_server/src/math_server.cpp
Labels: cherry-pick-to-NONE

#1896 [core] SetExclFilter, SetInclFilter, SetFilterState removed from monitoring API
  app/mon/mon_gui/src/ecalmon.cpp
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/topic_widget.cpp
  app/mon/mon_tui/src/main.cpp
  app/rec/rec_client_core/src/ecal_rec.cpp
  app/rec/rec_gui/src/main.cpp
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/cimpl/ecal_monitoring_cimpl.h
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/config/monitoring.h
  ecal/core/include/ecal/ecal_config.h
  ecal/core/include/ecal/ecal_monitoring.h
  ecal/core/src/cimpl/ecal_monitoring_cimpl.cpp
  ecal/core/src/config/builder/monitoring_attribute_builder.cpp
  ecal/core/src/config/builder/monitoring_attribute_builder.h
  ecal/core/src/config/configuration_reader.cpp
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/configuration_to_yaml.h
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/config/ecal_config_initializer.cpp
  ecal/core/src/ecal_config_internal.h
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/monitoring/config/attributes/monitoring_attributes.h
  ecal/core/src/monitoring/ecal_monitoring_def.cpp
  ecal/core/src/monitoring/ecal_monitoring_def.h
  ecal/core/src/monitoring/ecal_monitoring_filter.cpp
  ecal/core/src/monitoring/ecal_monitoring_filter.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.h
  ecal/tests/CMakeLists.txt
  ecal/tests/cpp/config_test/src/config_test.cpp
  ecal/tests/cpp/monitoring_test/CMakeLists.txt
  ecal/tests/cpp/monitoring_test/src/monitoring_filter_test.cpp
  lang/python/core/ecal/core/core.py
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1897 [gh actions] Correct naming for Ubuntu versions
  .github/workflows/build-ubuntu.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1889 [config] Modernized config path handling
  .github/workflows/build-ubuntu.yml
  app/play/play_core/include/ecal_play_logger.h
  app/rec/rec_client_core/include/rec_client_core/ecal_rec_logger.h
  app/sys/sys_client_core/include/sys_client_core/ecal_sys_client_logger.h
  app/sys/sys_core/include/ecalsys/ecal_sys_logger.h
  app/sys/sys_gui/src/widgets/import_from_cloud_widget/import_from_cloud_widget.cpp
  contrib/ecaltime/linuxptp/src/config/config.h
  ecal/core/CMakeLists.txt
  ecal/core/cfg/gen/CMakeLists.txt
  ecal/core/cfg/gen/generate_configuration_yaml.cpp
  ecal/core/include/ecal/config/logging.h
  ecal/core/include/ecal/ecal_util.h
  ecal/core/src/config/builder/logging_attribute_builder.cpp
  ecal/core/src/config/configuration.cpp
  ecal/core/src/config/configuration_writer.cpp
  ecal/core/src/config/configuration_writer.h
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/config/default_configuration.h
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/config/ecal_path_processing.cpp
  ecal/core/src/config/ecal_path_processing.h
  ecal/core/src/config/transport_layer.cpp
  ecal/core/src/ecal_def.h
  ecal/core/src/ecal_util.cpp
  ecal/core/src/logging/ecal_log_provider.cpp
  ecal/tests/cpp/config_test/CMakeLists.txt
  ecal/tests/cpp/config_test/src/path_processing_test.cpp
  thirdparty/gtest/build-gtest.cmake
Labels: cherry-pick-to-NONE

#1900 [app] mma-network-send-receive-fix
  contrib/mma/include/windows/mma_windows.h
  contrib/mma/src/windows/mma_windows.cpp
Labels: cherry-pick-to-NONE

#1906 [GH Action] Removed Python 3.7 build on windows [5.12]
  .github/workflows/build-windows.yml
Labels: Auto Approve

#1905 [GH Action] Removed Python 3.7 build on windows [5.13]
  .github/workflows/build-windows.yml
Labels: Auto Approve

#1903 [doc] Added support for multiversion documentation [5.12]
  .github/workflows/documentation.yml
  doc/rst/conf.py
Labels: Auto Approve, cherry-pick-to-NONE

#1902 [doc] Added support for multiversion documentation [5.13]
  .github/workflows/documentation.yml
  doc/rst/conf.py
Labels: Auto Approve, cherry-pick-to-NONE

#1901 [doc] Added support for multiversion documentation [master]
  .github/workflows/documentation.yml
  doc/rst/conf.py
Labels: Auto Approve, cherry-pick-to-NONE

#1908 Fix broken wheel build.
  pyproject.toml
  thirdparty/hdf5/build-hdf5.cmake
Labels: Auto Approve, cherry-pick-to-NONE

#1907 [build] windows cmake options fixed
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  build_win/win_make_cmake.bat
  build_win/win_make_python_wheel.bat
  doc/rst/development/building_ecal_from_source.rst
  doc/rst/development/ecal_cmake_options.rst
  lang/python/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1911 [core] 3 minor warnings fixed
  ecal/core/src/config/ecal_path_processing.cpp
Labels: cherry-pick-to-NONE

#1910 [config] Removed template definition from src file to inline
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/configuration_to_yaml.h
Labels: cherry-pick-to-NONE

#1909 [core] Introduce config_file_path as new field in monitoring.
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/process_widget.cpp
  app/mon/mon_gui/src/widgets/models/process_tree_item.cpp
  app/mon/mon_gui/src/widgets/models/process_tree_item.h
  app/mon/mon_gui/src/widgets/models/process_tree_model.h
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/registration/ecal_process_registration.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_struct_sample_registration.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/datatype.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/datatype.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/ecal.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/ecal.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/host.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/host.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/layer.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/layer.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/logging.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/logging.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/monitoring.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/monitoring.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/process.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/process.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/service.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/service.npb.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.h
  ecal/core/src/serialization/nanopb/pb.h
  ecal/core/src/serialization/nanopb/pb_decode.c
  ecal/core_pb/src/ecal/core/pb/process.proto
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  ecal/tests/cpp/serialization_test/src/registration_generate.cpp
Labels: cherry-pick-to-NONE

#1919 [core] Rename TopicIDCallbackT to TopicEventCallbackT.
  ecal/core/include/ecal/ecal_registration.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/registration/ecal_registration.cpp
Labels: cherry-pick-to-NONE

#1922 [cmake] Remove old helper functions
  cmake/helper_functions/ecal_add_functions.cmake
  cmake/helper_functions/ecal_install_functions.cmake
  ecal/core/CMakeLists.txt
  lang/c/core/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1921 [core] event handling cleanup
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  lang/c/core/src/ecal_publisher_cimpl.cpp
  lang/c/core/src/ecal_subscriber_cimpl.cpp
  lang/c/tests/core_test/src/core_test.cpp
  lang/python/core/src/ecal_clang.cpp
  serialization/protobuf/samples/pubsub/person_events_rec/src/person_events_rec.cpp
  serialization/protobuf/samples/pubsub/person_events_snd/src/person_events_snd.cpp
Labels: cherry-pick-to-NONE

#1923 [core] Rename Methods regarding Server/Client:
  ecal/core/include/ecal/ecal_registration.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/registration/ecal_registration.cpp
  ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp
  ecal/tests/cpp/descgate_test/src/descgate_getentities.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1917 [config] Small hotfix for path_processing and logging to file
  app/sys/sys_gui/src/widgets/import_from_cloud_widget/import_from_cloud_widget.cpp
  ecal/core/include/ecal/config/configuration.h
  ecal/core/src/config/configuration.cpp
  ecal/core/src/config/ecal_config.cpp
  ecal/core/src/config/ecal_config_initializer.cpp
  ecal/core/src/config/ecal_path_processing.cpp
  ecal/core/src/config/ecal_path_processing.h
  ecal/core/src/logging/ecal_log_provider.cpp
  ecal/core/src/registration/ecal_process_registration.cpp
  ecal/tests/cpp/config_test/src/path_processing_test.cpp
Labels: cherry-pick-to-NONE

#1924 [cmake] add missing enable_testing call.
  lang/c/CMakeLists.txt
Labels: cherry-pick-to-NONE

#1925 [Process] Unit name handling
  ecal/core/include/ecal/ecal_core.h
  ecal/core/src/ecal.cpp
  ecal/core/src/ecal_global_accessors.cpp
  ecal/tests/cpp/core_test/CMakeLists.txt
  ecal/tests/cpp/core_test/src/core_test.cpp
  lang/c/core/include/ecal/cimpl/ecal_core_cimpl.h
  lang/c/core/src/ecal_core_cimpl.cpp
  lang/c/tests/core_test/CMakeLists.txt
  lang/c/tests/core_test/src/core_test.cpp
  lang/python/core/ecal/core/core.py
  lang/python/core/src/ecal_clang.cpp
  lang/python/core/src/ecal_clang.h
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1928 [core] linux warning fix (RelocatableCircularQueue)
  ecal/core/src/registration/shm/relocatable_circular_queue.h
Labels: cherry-pick-to-NONE

#1899 [python] missing monitoring attributes added
  build_win/Readme.md
  build_win/win_make_all.bat
  build_win/win_make_python_wheel.bat
  cpack/innosetup/ecal_setup.iss.in
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#1927 [core] linux warning fixes
  ecal/core/CMakeLists.txt
  ecal/core/src/logging/ecal_log_provider.cpp
  ecal/core/src/logging/ecal_log_receiver.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
Labels: cherry-pick-to-NONE

#1930 eCAL core v5 compatibility modus (part 1)
  app/play/play_core/src/measurement_container.h
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/include/ecal/ecal_client.h
  ecal/core/include/ecal/ecal_client_instance.h
  ecal/core/include/ecal/ecal_namespace.h
  ecal/core/include/ecal/ecal_publisher.h
  ecal/core/include/ecal/ecal_server.h
  ecal/core/include/ecal/ecal_subscriber.h
  ecal/core/include/ecal/msg/dynamic.h
  ecal/core/include/ecal/msg/publisher.h
  ecal/core/include/ecal/msg/subscriber.h
  ecal/core/include/ecal/v5/ecal_callback.h
  ecal/core/include/ecal/v5/ecal_client.h
  ecal/core/include/ecal/v5/ecal_publisher.h
  ecal/core/include/ecal/v5/ecal_server.h
  ecal/core/include/ecal/v5/ecal_subscriber.h
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_servicegate.cpp
  ecal/core/src/service/ecal_servicegate.h
  ecal/core/src/v5/pubsub/ecal_publisher.cpp
  ecal/core/src/v5/pubsub/ecal_subscriber.cpp
  ecal/core/src/v5/service/ecal_service_client.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.h
  ecal/core/src/v5/service/ecal_service_server.cpp
  ecal/core/src/v5/service/ecal_service_server_impl.cpp
  ecal/core/src/v5/service/ecal_service_server_impl.h
  ecal/samples/cpp/pubsub/binary/ping/src/ping.cpp
  ecal/samples/cpp/pubsub/binary/pong/src/pong.cpp
  ecal/tests/cpp/clientserver_v5_test/src/clientserver_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_callback_topicid.cpp
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_connection_test.cpp
  lang/c/core/src/ecal_client_cimpl.cpp
  lang/c/core/src/ecal_publisher_cimpl.cpp
  lang/c/core/src/ecal_server_cimpl.cpp
  lang/c/core/src/ecal_subscriber_cimpl.cpp
  lang/csharp/Continental.eCAL.Core/ecal_clr.h
  lang/python/core/src/ecal_clang.cpp
  lang/python/core/src/ecal_wrap.cxx
  serialization/capnproto/capnproto/include/ecal/msg/capnproto/publisher.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/publisher.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/server.h
Labels: cherry-pick-to-NONE

#1933 Feature/ecal service namespace
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_service_singleton_manager.cpp
  ecal/core/src/service/ecal_service_singleton_manager.h
  ecal/service/ecal_service/CMakeLists.txt
  ecal/service/ecal_service/include/ecal/service/client_manager.h
  ecal/service/ecal_service/include/ecal/service/client_session.h
  ecal/service/ecal_service/include/ecal/service/error.h
  ecal/service/ecal_service/include/ecal/service/logger.h
  ecal/service/ecal_service/include/ecal/service/server.h
  ecal/service/ecal_service/include/ecal/service/server_manager.h
  ecal/service/ecal_service/include/ecal_service/client_manager.h
  ecal/service/ecal_service/include/ecal_service/client_session.h
  ecal/service/ecal_service/include/ecal_service/client_session_types.h
  ecal/service/ecal_service/include/ecal_service/error.h
  ecal/service/ecal_service/include/ecal_service/logger.h
  ecal/service/ecal_service/include/ecal_service/server.h
  ecal/service/ecal_service/include/ecal_service/server_manager.h
  ecal/service/ecal_service/include/ecal_service/server_session_types.h
  ecal/service/ecal_service/include/ecal_service/state.h
  ecal/service/ecal_service/src/client_manager.cpp
  ecal/service/ecal_service/src/client_session.cpp
  ecal/service/ecal_service/src/client_session_impl_base.h
  ecal/service/ecal_service/src/client_session_impl_v1.cpp
  ecal/service/ecal_service/src/client_session_impl_v1.h
  ecal/service/ecal_service/src/log_defs.h
  ecal/service/ecal_service/src/log_helpers.h
  ecal/service/ecal_service/src/protocol_layout.h
  ecal/service/ecal_service/src/protocol_v1.cpp
  ecal/service/ecal_service/src/protocol_v1.h
  ecal/service/ecal_service/src/server.cpp
  ecal/service/ecal_service/src/server_impl.cpp
  ecal/service/ecal_service/src/server_impl.h
  ecal/service/ecal_service/src/server_manager.cpp
  ecal/service/ecal_service/src/server_session_impl_base.h
  ecal/service/ecal_service/src/server_session_impl_v1.cpp
  ecal/service/ecal_service/src/server_session_impl_v1.h
  ecal/service/samples/sample_client/src/main.cpp
  ecal/service/samples/sample_server/src/main.cpp
  ecal/service/samples/sample_standalone/src/main.cpp
  ecal/service/test/src/ecal_tcp_service_test.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#1934 [core] rearrange service and pubsub headers into folders.
  app/rec/rec_client_core/src/ecal_rec_impl.h
  app/rec/rec_client_core/src/frame.h
  app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
  app/sys/sys_cli/src/commands/command.h
  app/sys/sys_cli/src/commands/helpers.h
  app/sys/sys_cli/src/ecalsys_cli.cpp
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/ecal.h
  ecal/core/include/ecal/ecal_callback.h
  ecal/core/include/ecal/ecal_process.h
  ecal/core/include/ecal/ecal_registration.h
  ecal/core/include/ecal/ecal_types.h
  ecal/core/include/ecal/pubsub/payload_writer.h
  ecal/core/include/ecal/pubsub/publisher.h
  ecal/core/include/ecal/pubsub/subscriber.h
  ecal/core/include/ecal/pubsub/types.h
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/client_instance.h
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/service/types.h
  ecal/core/include/ecal/v5/ecal_callback.h
  ecal/core/include/ecal/v5/ecal_client.h
  ecal/core/include/ecal/v5/ecal_publisher.h
  ecal/core/include/ecal/v5/ecal_server.h
  ecal/core/src/ecal_descgate.h
  ecal/core/src/io/shm/ecal_memfile.h
  ecal/core/src/io/shm/ecal_memfile_sync.h
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/readwrite/ecal_writer_base.h
  ecal/core/src/readwrite/ecal_writer_buffer_payload.h
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/v5/service/ecal_service_client.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.h
  ecal/core/src/v5/service/ecal_service_server_impl.h
  ecal/samples/cpp/benchmarks/datarate_rec/src/datarate_rec.cpp
  ecal/samples/cpp/benchmarks/datarate_snd/src/datarate_snd.cpp
  ecal/samples/cpp/benchmarks/latency_snd/src/binary_payload_writer.h
  ecal/samples/cpp/benchmarks/performance_rec/src/performance_rec.cpp
  ecal/samples/cpp/benchmarks/performance_snd/src/binary_payload_writer.h
  ecal/samples/cpp/benchmarks/performance_snd/src/performance_snd.cpp
  ecal/samples/cpp/benchmarks/perftool/src/publisher.h
  ecal/samples/cpp/benchmarks/perftool/src/subscriber.h
  ecal/samples/cpp/benchmarks/pubsub_throughput/src/binary_payload_writer.h
  ecal/samples/cpp/misc/timer/src/timer.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_acknowledge.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_multibuffer.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_udp.cpp
  lang/c/core/src/ecal_client_cimpl.cpp
Labels: cherry-pick-to-NONE

#1932 [v5::service_client] Filter eventcalls by hostname in ecal_service_client_v5_impl
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
Labels: cherry-pick-to-NONE

#1937 [core] move SServiceResponse (old API) to v5/ecal_callback.h
  app/rec/rec_server_cli/src/commands/command.cpp
  app/rec/rec_server_core/src/recorder/remote_recorder.cpp
  app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
  app/sys/sys_cli/src/commands/command.cpp
  app/sys/sys_core/src/connection/remote_connection.cpp
  ecal/core/include/ecal/service/types.h
  ecal/core/include/ecal/v5/ecal_callback.h
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/samples/cpp/orchestration/orchestrator/src/orchestrator.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/clientserver_v5_test/src/clientserver_test.cpp
  lang/c/core/src/ecal_client_cimpl.cpp
  lang/csharp/Continental.eCAL.Core/ecal_clr.cpp
  lang/python/core/src/ecal_wrap.cxx
  samples/cpp/services/ecalplayer_client/src/ecalplayer_client.cpp
  samples/cpp/services/ecalplayer_gui_client/src/ecalplayer_gui_client.cpp
  samples/cpp/services/ecalplayer_gui_client/src/ecalplayer_gui_client.h
  samples/cpp/services/ecalsys_client/src/ecalsys_client.cpp
  samples/cpp/services/rec_client_service_cli/src/ecalrecorder_client.cpp
  samples/cpp/services/rec_client_service_gui/src/EcalrecGuiClient.cpp
  samples/cpp/services/rec_client_service_gui/src/EcalrecGuiClient.h
  samples/cpp/services/rec_server_service_gui/src/rec_server_service_gui.cpp
  samples/cpp/services/rec_server_service_gui/src/rec_server_service_gui.h
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h
  serialization/protobuf/samples/services/math_client/src/math_client.cpp
  serialization/protobuf/samples/services/ping_client/src/ping_client.cpp
  serialization/protobuf/tests/clientserver_proto_test/src/clientserver_test_proto.cpp
Labels: cherry-pick-to-NONE

#1936 Update doxygen to latest version.
  .github/workflows/build-windows.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1938 [core] Move MethodCallbackT to v5/ecal_callback.h
  ecal/core/include/ecal/service/types.h
  ecal/core/include/ecal/v5/ecal_callback.h
Labels: cherry-pick-to-NONE

#1941 Harmonize Server API
  ecal/core/include/ecal/registration.h
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/service/types.h
  ecal/core/include/ecal/v5/ecal_client.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/registration/ecal_registration.cpp
  ecal/core/src/serialization/ecal_struct_sample_common.h
  ecal/core/src/serialization/ecal_struct_service.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/v5/service/ecal_service_client.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.h
  ecal/core/src/v5/service/ecal_service_server_impl.cpp
  ecal/core/src/v5/service/ecal_service_server_impl.h
  ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp
  ecal/samples/cpp/services/latency_server/src/latency_server.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1943 [core] Fixed topic resubscription via shared memory
  ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
Labels: cherry-pick-to-NONE

#1947 [cmake] Optional C bindings
  CMakeLists.txt
Labels: cherry-pick-to-NONE

#1950 [cmake] one more linkage attribute corrected.
  app/play/play_gui/CMakeLists.txt
Labels: Auto Approve, cherry-pick-to-NONE

#1916 [test: shm] Add testcase for fast reconnection
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
Labels: cherry-pick-to-NONE

#1953 [core] service renaming and comments.
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/service/types.h
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/core/src/v5/service/ecal_service_server_impl.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
Labels: cherry-pick-to-NONE

#1952 [core] Marked StartProcess() and StopProcess() as deprecated
  ecal/core/include/ecal/process.h
Labels: cherry-pick-to-NONE

#1957 [core] remove namespace v6, keep v5. Remove build of compatibility ta…
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/pubsub/publisher.h
  ecal/core/include/ecal/pubsub/subscriber.h
  ecal/core/include/ecal/pubsub/types.h
  ecal/core/include/ecal/registration.h
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/client_instance.h
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/service/types.h
  ecal/core/include/ecal/v5/ecal_client.h
  ecal/core/include/ecal/v5/ecal_subscriber.h
  ecal/core/src/ecal_descgate.cpp
  ecal/core/src/ecal_descgate.h
  ecal/core/src/pubsub/ecal_publisher.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/registration/ecal_registration.cpp
  ecal/core/src/service/ecal_clientgate.cpp
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/service/ecal_service_server_impl.cpp
  ecal/core/src/service/ecal_service_server_impl.h
  ecal/core/src/service/ecal_servicegate.cpp
  ecal/core/src/service/ecal_servicegate.h
  ecal/core/src/v5/pubsub/ecal_subscriber.cpp
  ecal/core/src/v5/service/ecal_service_client.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.h
  ecal/core/src/v5/service/ecal_service_server_impl.cpp
  ecal/core/src/v5/service/ecal_service_server_impl.h
  ecal/samples/cpp/services/latency_client/src/latency_client.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1958 [flatbuffers] fix monster_rec sample.
  serialization/flatbuffers/samples/pubsub/monster_rec/monster_rec.cpp
Labels: cherry-pick-to-NONE

#1960 [core] remove ecal/callback.h
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/callback.h
  ecal/core/include/ecal/ecal.h
  ecal/core/include/ecal/v5/ecal_subscriber.h
  ecal/core/src/service/ecal_clientgate.h
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_server_impl.h
Labels: cherry-pick-to-NONE

#1961 [core] Limit frequency values on registration layer so they don't bec…
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
Labels: cherry-pick-to-NONE

#1965 External Release page
  .github/workflows/documentation-release-page.yml
  .gitignore
  doc/_static/css/bignums.css
  doc/_static/css/sphinx-book-theme-1.1.2-ecaladdon.css
  doc/_static/css/tabs-3.4.5-ecaladdon.css
  doc/_static/img/ecal-logo.svg
  doc/_static/img/favicon.png
  doc/_templates/footer.html
  doc/extensions/generate_release_page.py
  doc/extensions/resource/release_page.rst.jinja
  doc/extensions/resource/release_page_index.rst.jinja
  doc/include.txt
  doc/release_page/conf.py
  doc/release_page/generate_release_documentation/__init__.py
  doc/release_page/resource/release_page.rst.jinja
  doc/release_page/resource/release_page_index.rst.jinja
Labels: Auto Approve, cherry-pick-to-NONE

#1966 [clang-tidy] Disabled performance-avoid-endl warning
  .clang-tidy
Labels: cherry-pick-to-NONE

#1970 [core] removed "abc" as default ecal yaml file path.
  ecal/core/include/ecal/config/configuration.h
Labels: cherry-pick-to-NONE

#1968 [cmake] Renamed CMake Options
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  CMakePresets.json
  app/mon/mon_gui/CMakeLists.txt
  app/mon/mon_gui/src/ecalmon.cpp
  app/mon/mon_plugins/CMakeLists.txt
  app/rec/rec_client_core/CMakeLists.txt
  build_win/win_make_cmake.bat
  colcon.pkg
  conanfile.py
  contrib/mma/README.md
  cpack/cpack_variables.cmake
  doc/rst/development/building_ecal_from_source.rst
  doc/rst/development/ecal_cmake_options.rst
  ecal/CMakeLists.txt
  ecal/core/cfg/CMakeLists.txt
  ecal/ecal-core-options.cmake
  ecal/samples/CMakeLists.txt
  lang/python/CMakeLists.txt
  lang/python/samples/CMakeLists.txt
  pyproject.toml
  samples/CMakeLists.txt
  tests/contrib/cross/Makefile
Labels: cherry-pick-to-NONE

#1963 [core] Removed tlayer.h include and moved definitions to TransportLayer configuration
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/config.h
  ecal/core/include/ecal/config/publisher.h
  ecal/core/include/ecal/config/transport_layer.h
  ecal/core/include/ecal/ecal.h
  ecal/core/include/ecal/tlayer.h
  ecal/core/src/config/configuration_to_yaml.cpp
  ecal/core/src/config/default_configuration.cpp
  ecal/core/src/ecal_config_internal.h
  ecal/core/src/ecal_def.h
  ecal/core/src/pubsub/ecal_pubgate.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subgate.cpp
  ecal/core/src/readwrite/config/attributes/writer_attributes.h
  ecal/samples/cpp/benchmarks/pubsub_throughput/src/pubsub_throughput.cpp
Labels: cherry-pick-to-NONE

#1973 [GH Action] Updated CI buildwheel step
  .github/workflows/build_wheels.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1974 [GH Action] Addeded support/v6.0 to possible cherry-pick branches
  .github/workflows/cherry-pick-to.yml
Labels: Auto Approve, cherry-pick-to-NONE

#1955 [mon_gui] Change font for new and deleted/disconnected topics in mon_gui
  app/mon/mon_gui/src/widgets/ecalmon_tree_widget/topic_widget.cpp
  app/mon/mon_gui/src/widgets/models/group_tree_model.cpp
  app/mon/mon_gui/src/widgets/models/group_tree_model.h
  app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp
  app/mon/mon_gui/src/widgets/models/topic_tree_item.h
  app/mon/mon_gui/src/widgets/models/topic_tree_model.cpp
  app/mon/mon_gui/src/widgets/models/topic_tree_model.h
Labels: cherry-pick-to-NONE

#1969 [core] split `GetTopicNames` into `GetPublishedTopicNames` and `GetSubscribedTopicNames`.
  ecal/core/include/ecal/registration.h
  ecal/core/src/registration/ecal_registration.cpp
  ecal/samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
  ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp
  ecal/samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp
  lang/python/core/src/ecal_clang.cpp
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1975 [Topic] Remove remove user defined attributes for topics
  app/mon/mon_tui/src/model/monitor.hpp
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/serialization/ecal_serialize_common.cpp
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
  ecal/core/src/serialization/ecal_struct_sample_registration.h
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.c
  ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.h
  ecal/core_pb/src/ecal/core/pb/topic.proto
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
Labels: cherry-pick-to-NONE

#1980 [core] client eventcallback as reference and cmakelists whitespace alignment
  CMakeLists.txt
  ecal/core/CMakeLists.txt
  ecal/core/include/ecal/config.h
  ecal/core/include/ecal/config/configuration.h
  ecal/core/include/ecal/config/publisher.h
  ecal/core/include/ecal/config/transport_layer.h
  ecal/core/include/ecal/process_mode.h
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/server.h
  ecal/core/include/ecal/types/custom_data_types.h
  ecal/core/src/readwrite/config/attributes/reader_attributes.h
  ecal/core/src/readwrite/config/attributes/writer_attributes.h
  ecal/core/src/readwrite/config/builder/udp_attribute_builder.cpp
  ecal/core/src/registration/config/attributes/registration_attributes.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_server.cpp
  ecal/core/src/types/ecal_custom_data_types.cpp
  ecal/samples/cpp/misc/config/src/config_sample.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_acknowledge.cpp
Labels: cherry-pick-to-NONE

#1983 [config] Adapt config generation and yaml file distribution
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  cpack/innosetup/ecal_setup.iss.in
  ecal/CMakeLists.txt
  ecal/core/cfg/CMakeLists.txt
  ecal/core/cfg/gen/CMakeLists.txt
  ecal/core/cfg/generate_configuration_yaml.cpp
Labels: cherry-pick-to-NONE

#1982 Feature/subscriber callback
  app/mon/mon_plugins/raw_data_reflection/src/plugin_widget.cpp
  app/mon/mon_tui/src/tui/viewmodel/message_visualization/raw.hpp
  app/rec/rec_client_core/src/frame.h
  ecal/core/include/ecal/pubsub/types.h
  ecal/core/include/ecal/v5/ecal_callback.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/v5/pubsub/ecal_subscriber.cpp
  ecal/samples/cpp/benchmarks/counter_rec/src/counter_rec.cpp
  ecal/samples/cpp/benchmarks/datarate_rec/src/datarate_rec.cpp
  ecal/samples/cpp/benchmarks/latency_rec/src/latency_rec.cpp
  ecal/samples/cpp/benchmarks/performance_rec/src/performance_rec.cpp
  ecal/samples/cpp/benchmarks/perftool/src/subscriber.cpp
  ecal/samples/cpp/benchmarks/pubsub_throughput/src/pubsub_throughput.cpp
  ecal/samples/cpp/pubsub/binary/binary_rec/src/binary_rec.cpp
  ecal/samples/cpp/pubsub/binary/binary_zero_copy_rec/src/binary_zero_copy_rec.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_acknowledge.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_multibuffer.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
  ecal/tests/cpp/pubsub_test/src/pubsub_test_udp.cpp
  ecal/tests/cpp/pubsub_v5_test/src/pubsub_connection_test.cpp
  lang/c/core/src/subscriber.cpp
  lang/csharp/Continental.eCAL.Core/ecal_clr.cpp
  lang/csharp/Continental.eCAL.Core/ecal_clr.h
  lang/python/core/src/ecal_clang.cpp
  lang/python/core/src/ecal_wrap.cxx
  serialization/capnproto/samples/pubsub/addressbook_rec_dynamic/src/addressbook_rec_dynamic.cpp
  serialization/common/core/include/ecal/msg/dynamic.h
  serialization/common/core/include/ecal/msg/subscriber.h
  serialization/flatbuffers/samples/pubsub/monster_rec/monster_rec.cpp
  serialization/protobuf/samples/pubsub/person_loopback/src/person_loopback.cpp
Labels: cherry-pick-to-NONE

#1984 [core] introduced default timeout parameter for client service method calls
  ecal/core/include/ecal/service/client.h
  ecal/core/include/ecal/service/client_instance.h
  ecal/core/src/service/ecal_service_client.cpp
  ecal/core/src/service/ecal_service_client_impl.cpp
  ecal/core/src/service/ecal_service_client_impl.h
  ecal/core/src/service/ecal_service_client_instance.cpp
  ecal/core/src/v5/service/ecal_service_client_impl.cpp
  ecal/samples/cpp/services/latency_client/src/latency_client.cpp
  ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
  ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
  serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Labels: cherry-pick-to-NONE

#1985 [doc] Hello world src adaption to new API
  doc/rst/getting_started/src/hello_world/hello_world_rec/main.cpp
  doc/rst/getting_started/src/hello_world_protobuf/protobuf_rec/main.cpp
Labels: Auto Approve, cherry-pick-to-NONE

#1986 [mma] MMA init condition change.
  contrib/mma/src/mma_application.cpp
Labels: cherry-pick-to-NONE
