Repository eclipse-ecal/ecal, pull requests merged in 2025-07, with the labels that each got.

#2228 [fix] Remove some warnings in C samples.
  lang/c/tests/pubsub_test/src/pubsub_test.cpp
  lang/c/tests/services_test/src/services_test.cpp
Labels: cherry-pick-to-support/v6.0

#2235 [ecalhdf5] Fix bug of double escaping channel names.
  contrib/ecalhdf5/src/eh5_meas_api_v3.cpp
  contrib/ecalhdf5/src/eh5_meas_dir.cpp
  contrib/ecalhdf5/src/eh5_meas_dir.h
  contrib/ecalhdf5/src/eh5_meas_file_v1.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v1.h
  contrib/ecalhdf5/src/eh5_meas_file_v2.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v2.h
  contrib/ecalhdf5/src/eh5_meas_file_v3.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v3.h
  contrib/ecalhdf5/src/eh5_meas_file_v4.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v4.h
  contrib/ecalhdf5/src/eh5_meas_file_v5.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v5.h
  contrib/ecalhdf5/src/eh5_meas_file_v6.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v6.h
  contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp
  contrib/ecalhdf5/src/eh5_meas_file_writer_v5.h
  contrib/ecalhdf5/src/eh5_meas_file_writer_v6.cpp
  contrib/ecalhdf5/src/eh5_meas_file_writer_v6.h
  contrib/ecalhdf5/src/eh5_meas_impl.h
  contrib/ecalhdf5/src/escape.cpp
  contrib/ecalhdf5/src/escape.h
  tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Labels: cherry-pick-to-support/v6.0

#2234 [cmake] CMake deployment of third-party libraries
  CMakeLists.txt
  app/rec/rec_client_core/CMakeLists.txt
  cmake/helper_functions/ecal_helper_functions.cmake
  contrib/ecalhdf5/CMakeLists.txt
  lang/c/core/include/ecal_c/init.h
Labels: cherry-pick-to-support/v6.0

#2247 Fixed a critical race condition in eCAL's posix event implementation
  ecal/core/src/ecal_event.cpp
Labels: cherry-pick-to-support/v5.13, cherry-pick-to-support/v6.0

#2250 [CP #2247 > support/v5.13] Fixed a critical race condition in eCAL's linux event implementation
  ecal/core/src/ecal_event.cpp
Labels: Auto Approve

#2273 [doc] Adapted sample naming of person and mirror in documentation
  doc/include.txt
  doc/rst/getting_started/img/cloud_person_combined.png
  doc/rst/getting_started/img/samples_person.png
  doc/rst/getting_started/img/samples_service.png
  doc/rst/getting_started/img/samples_service_cloud_combined.png
  doc/rst/getting_started/network.rst
  doc/rst/getting_started/samples.rst
  doc/rst/getting_started/services.rst
  doc/rst/include.txt
Labels: cherry-pick-to-support/v6.0

#2282 [doc] Fixed some issues in different doc sections
  doc/rst/advanced/ecal_in_docker.rst
  doc/rst/development/ecal_cmake_options.rst
  doc/rst/getting_started/setup.rst
Labels: Auto Approve, cherry-pick-to-support/v6.0

#2280 [Sys] Added Ecal Parser Evaluation to target Hostname field
  app/sys/sys_cli/src/ecalsys_service.cpp
  app/sys/sys_cli/src/ecalsys_util.cpp
  app/sys/sys_core/src/ecal_sys.cpp
  app/sys/sys_core/src/ecal_sys_monitor.cpp
  app/sys/sys_core/src/taskaction_threads/start_task_list_thread.cpp
  app/sys/sys_core/src/taskaction_threads/stop_task_list_thread.cpp
  app/sys/sys_core/src/taskaction_threads/update_from_cloud_task_list_thread.cpp
  app/sys/sys_gui/src/ecalsys_service.cpp
  app/sys/sys_gui/src/widgets/groupwidget/group_widget.cpp
  app/sys/sys_gui/src/widgets/taskwidget/task_widget.cpp
  app/sys/sys_gui/src/widgets/taskwidget/task_widget.ui
  app/sys/sys_gui/src/widgets/treemodels/task_tree_item.cpp
Labels: cherry-pick-to-support/v6.0

#2281 [doc] some updates for eCAL 6 Release.
  contrib/ecalhdf5/include/ecalhdf5/eh5_meas_api_v3.h
  doc/rst/development/build_ecal.rst
  doc/rst/development/building_ecal_from_source.rst
  doc/rst/development/ecal_cmake_options.rst
  doc/rst/index.rst
  ecal/core/include/ecal/registration.h
  pyproject.toml
  thirdparty/nanobind/build-nanobind.cmake
  thirdparty/tsl-robin-map/build-tsl-robin-map.cmake
Labels: cherry-pick-to-support/v6.0

#2291 [Doc] Removed unnecessary empty code block
  doc/rst/configuration/local.rst
Labels: cherry-pick-to-support/v6.0
