Repository eclipse-ecal/ecal, pull requests merged in 2025-04, with the labels that each got.

#2098 [docu] eCAL 6 migration guide
  doc/rst/ecal_6_migration.rst
  doc/rst/index.rst
Labels: cherry-pick-to-NONE

#2096 renamed send/receiver for c samples
  lang/c/samples/CMakeLists.txt
  lang/c/samples/pubsub/string/hello_receive/CMakeLists.txt
  lang/c/samples/pubsub/string/hello_receive/src/hello_receive.c
  lang/c/samples/pubsub/string/hello_send/CMakeLists.txt
  lang/c/samples/pubsub/string/hello_send/src/hello_send.c
  serialization/string/samples/pubsub/hello_send/src/hello_send.cpp
Labels: cherry-pick-to-NONE

#2100 Fixing description of string publisher class
  serialization/string/string/include/ecal/msg/string/publisher.h
Labels: cherry-pick-to-NONE

#2104 [Doc] Moved Migration Guide and added 6.0 Release skeleton
  doc/rst/index.rst
  doc/rst/versions/6.0/compatibility_table.txt
  doc/rst/versions/6.0/migration_guide.rst
  doc/rst/versions/6.0/whats_new.rst
  doc/rst/versions/compatibility.rst
  doc/rst/versions/ecal_versions.rst
Labels: cherry-pick-to-NONE

#2103 [bugfix] Allow compatibility with CMake 4.0
  cmake/helper_functions/ecal_helper_functions.cmake
  doc/samples/cpp/configuration/hello_config/CMakeLists.txt
  doc/samples/cpp/configuration/publisher_config/CMakeLists.txt
  doc/samples/cpp/protobuf/hello_world_rec/CMakeLists.txt
  doc/samples/cpp/protobuf/hello_world_snd/CMakeLists.txt
  doc/samples/cpp/string/hello_world_rec/CMakeLists.txt
  doc/samples/cpp/string/hello_world_snd/CMakeLists.txt
  thirdparty/protobuf/build-protobuf.cmake
  thirdparty/termcolor/build-termcolor.cmake
  thirdparty/yaml-cpp/build-yaml-cpp.cmake
Labels: cherry-pick-to-NONE

#2102 [core] Removed "Mon" suffix from monitoring structs and fixed spelling of vector field names
  ecal/core/include/ecal/types/monitoring.h
  ecal/core/src/monitoring/ecal_monitoring_impl.cpp
  ecal/core/src/monitoring/ecal_monitoring_impl.h
  ecal/core/src/serialization/ecal_serialize_monitoring.cpp
  ecal/samples/cpp/monitoring/monitoring_performance/src/monitoring_performance.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.cpp
  ecal/tests/cpp/serialization_test/src/monitoring_generate.h
  lang/c/core/include/ecal_c/types/monitoring.h
  lang/c/core/src/monitoring.cpp
  lang/python/core/src/ecal_wrap.cxx
Labels: cherry-pick-to-NONE

#2108 CI: Use shallow submodules and more system packages
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-windows.yml
  .github/workflows/build_wheels.yml
  contrib/ecaltime/linuxptp/CMakeLists.txt
  ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
  thirdparty/yaml-cpp/compatibility-yaml-cpp.cmake
Labels: cherry-pick-to-NONE

#2110 core/minor-fixes-2025-04-07
  CMakeLists.txt
  ecal/core/include/ecal/config/logging.h
Labels: cherry-pick-to-NONE

#2113 samples/topic name alignment
  lang/c/samples/pubsub/string/hello_receive/src/hello_receive.c
  lang/c/samples/pubsub/string/hello_send/src/hello_send.c
  lang/csharp/Eclipse.eCAL.String.Samples/pubsub/string_rec_csharp.cs
  lang/csharp/Eclipse.eCAL.String.Samples/pubsub/string_snd_csharp.cs
  lang/python/samples/core/pubsub/string_rec.py
  lang/python/samples/core/pubsub/string_rec_cb.py
  lang/python/samples/core/pubsub/string_snd.py
  serialization/string/samples/pubsub/hello_receive/src/hello_receive.cpp
  serialization/string/samples/pubsub/hello_send/src/hello_send.cpp
Labels: cherry-pick-to-NONE

#2109 [build] Fix binary tree directory of submodule dependencies
  thirdparty/cmakefunctions/build-cmakefunctions.cmake
  thirdparty/curl/build-curl.cmake
  thirdparty/ecaludp/build-ecaludp.cmake
  thirdparty/fineftp/build-fineftp.cmake
  thirdparty/ftxui/build-ftxui.cmake
  thirdparty/gtest/build-gtest.cmake
  thirdparty/hdf5/build-hdf5.cmake
  thirdparty/protobuf/build-protobuf.cmake
  thirdparty/qwt/build-qwt.cmake
  thirdparty/recycle/build-recycle.cmake
  thirdparty/spdlog/build-spdlog.cmake
  thirdparty/tclap/build-tclap.cmake
  thirdparty/tcp_pubsub/build-tcp_pubsub.cmake
  thirdparty/termcolor/build-termcolor.cmake
  thirdparty/tinyxml2/build-tinyxml2.cmake
  thirdparty/udpcap/build-udpcap.cmake
  thirdparty/yaml-cpp/build-yaml-cpp.cmake
Labels: cherry-pick-to-NONE

#2112 [fix] Mutex and test ODR violations
  ecal/core/src/io/mtx/linux/ecal_named_mutex_impl.cpp
  ecal/core/src/io/mtx/linux/ecal_named_mutex_impl.h
  ecal/core/src/io/mtx/linux/ecal_named_mutex_robust_clocklock_impl.cpp
  ecal/core/src/io/mtx/linux/ecal_named_mutex_robust_clocklock_impl.h
  ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp
  ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
Labels: cherry-pick-to-NONE

#2099 [setup] Set eCAL Launcher to be linked on the userdesktop instead of common desktop
  cpack/innosetup/ecal_setup.iss.in
Labels: cherry-pick-to-NONE

#2121 [GH Action] Updated and exteded comments in cherry-pick action
  .github/workflows/cherry-pick-to.yml
Labels: Auto Approve, cherry-pick-to-NONE

#2123 [core] Fixed const correctness of CServiceServer and wrong return type of CMessagePublisher
  ecal/core/include/ecal/service/server.h
  ecal/core/src/service/ecal_service_server.cpp
  serialization/common/common/include/ecal/msg/publisher.h
Labels: cherry-pick-to-NONE

#2125 fix: Use asio to validate ipv4 address strings instead of regex
  ecal/core/include/ecal/types/custom_data_types.h
  ecal/core/src/types/ecal_custom_data_types.cpp
  ecal/tests/cpp/config_test/src/config_test.cpp
Labels: cherry-pick-to-NONE

#2126 Align service samples across C++, C and C#.
  ecal/samples/CMakeLists.txt
  ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp
  ecal/samples/cpp/services/mirror_client/CMakeLists.txt
  ecal/samples/cpp/services/mirror_client/src/mirror_client.cpp
  ecal/samples/cpp/services/mirror_server/CMakeLists.txt
  ecal/samples/cpp/services/mirror_server/src/mirror_server.cpp
  lang/c/samples/CMakeLists.txt
  lang/c/samples/services/minimal_client_c/src/minimal_client_c.c
  lang/c/samples/services/mirror_client_c/CMakeLists.txt
  lang/c/samples/services/mirror_client_c/src/mirror_client_c.c
  lang/c/samples/services/mirror_server_c/CMakeLists.txt
  lang/c/samples/services/mirror_server_c/src/mirror_server_c.c
  lang/csharp/Eclipse.eCAL.Core.Samples/service/CMakeLists.txt
  lang/csharp/Eclipse.eCAL.Core.Samples/service/minimal_server_csharp.cs
  lang/csharp/Eclipse.eCAL.Core.Samples/service/mirror_client_csharp.cs
  lang/csharp/Eclipse.eCAL.Core.Samples/service/mirror_server_csharp.cs
Labels: cherry-pick-to-NONE

#2128 [core] Changed return behavior of CServiceClient::CallWithXXX methods and fixed ServiceResponseVec assignment in C binding
  ecal/core/include/ecal/service/client.h
  ecal/core/src/service/ecal_service_client.cpp
  lang/c/core/include/ecal_c/service/client.h
  lang/c/core/src/common.h
Labels: cherry-pick-to-NONE

#2129 [lang] Fixed qnx build issues in C binding
  lang/c/core/CMakeLists.txt
  lang/c/core/src/auxiliaries.cpp
  lang/c/core/src/client.cpp
  lang/c/core/src/common.cpp
  lang/c/core/src/common.h
  lang/c/core/src/configuration.cpp
  lang/c/core/src/configuration.h
  lang/c/core/src/monitoring.cpp
  lang/c/core/src/process.cpp
  lang/c/core/src/publisher.cpp
  lang/c/core/src/server.cpp
  lang/c/core/src/subscriber.cpp
  lang/c/core/src/time.cpp
Labels: cherry-pick-to-NONE

#2131 [core] Remove ECAL_DATE, ECAL_VERSION from def.h
  CMakeLists.txt
  app/mma/src/mma_application.cpp
  app/mon/mon_gui/CMakeLists.txt
  app/play/play_core/src/ecal_play.cpp
  app/play/play_gui/CMakeLists.txt
  app/rec/rec_client_cli/src/ecal_rec_cli.cpp
  app/rec/rec_gui/CMakeLists.txt
  app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
  app/sys/sys_core/src/ecal_sys.cpp
  app/sys/sys_gui/CMakeLists.txt
  app/util/launcher/CMakeLists.txt
  ecal/core/CMakeLists.txt
  ecal/core/src/defs.h.in
  ecal/core/src/ecal.cpp
  ecal/core/src/ecal_process.cpp
  ecal/core/src/git_version.h.in
  ecal/tests/cpp/core_test/CMakeLists.txt
  lang/c/core/CMakeLists.txt
  lang/c/tests/core_test/CMakeLists.txt
  lang/csharp/Eclipse.eCAL.Core/ecal_clr_core.cpp
  lang/python/core/src/ecal_clang.cpp
Labels: cherry-pick-to-NONE

#2134 [CI] Use ccache on MacOS
  .github/actions/ccache-prepare/action.yml
  .github/actions/ccache-save/action.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  doc/CMakeLists.txt
Labels: cherry-pick-to-NONE

#2140 [CI] Use ccache on MacOS (#2134) - cherry-pick
  .github/actions/ccache-prepare/action.yml
  .github/actions/ccache-save/action.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-ubuntu.yml
  doc/CMakeLists.txt
Labels: Auto Approve, cherry-pick-to-NONE

#2138 [csharp] Make CMAKE_DOTNET_TARGE_FRAMEWORK_VERSION a cached variable.
  lang/csharp/CMakeLists.txt
Labels: cherry-pick-to-support/v6.0

#2139 [cmake] Disable C binding build for wheels.
  CMakeLists.txt
  CMakePresets.json
  lang/python/core/CMakeLists.txt
  pyproject.toml
Labels: cherry-pick-to-support/v6.0
