Repository eclipse-ecal/ecal, pull requests merged in 2025-09, with the labels that each got.

#2353 [docu] Added compatibility information and small change in msg drops info.
  doc/rst/advanced/message_drops.rst
  doc/rst/versions/6.0/compatibility_table.txt
Labels: cherry-pick-to-support/v6.0

#2342 [ecal_mon_tui] Set frequency calculation to Hz
  app/mon/mon_tui/src/model/data/topic.hpp
  app/mon/mon_tui/src/model/monitor.hpp
  app/mon/mon_tui/src/tui/viewmodel/topics.hpp
Labels: cherry-pick-to-support/v6.0

#2354 [GH Action] Added Action to genereate the sdv-manifest.toml
  .github/workflows/eclipse-sdv-maturity-assessment.yml
Labels: Auto Approve, cherry-pick-to-support/v5.13, cherry-pick-to-support/v6.0

#2365 [core] Process state structure
  ecal/core/include/ecal/types/process.h
  ecal/core/src/ecal_global_accessors.cpp
  ecal/core/src/ecal_global_accessors.h
  ecal/core/src/ecal_process.cpp
  ecal/core/src/registration/ecal_process_registration.cpp
Labels: cherry-pick-to-support/v6.0

#2373 [hdf5] Add function to retrieve data from measurement into a std::string
  contrib/ecalhdf5/include/ecalhdf5/eh5_meas_api_v2.h
  contrib/ecalhdf5/include/ecalhdf5/eh5_meas_api_v3.h
  contrib/ecalhdf5/src/eh5_meas_api_v2.cpp
  contrib/ecalhdf5/src/eh5_meas_api_v3.cpp
  contrib/ecalhdf5/src/eh5_meas_dir.cpp
  contrib/ecalhdf5/src/eh5_meas_dir.h
  contrib/ecalhdf5/src/eh5_meas_file_v1.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v1.h
  contrib/ecalhdf5/src/eh5_meas_file_v2.cpp
  contrib/ecalhdf5/src/eh5_meas_file_v2.h
  contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp
  contrib/ecalhdf5/src/eh5_meas_file_writer_v5.h
  contrib/ecalhdf5/src/eh5_meas_file_writer_v6.cpp
  contrib/ecalhdf5/src/eh5_meas_file_writer_v6.h
  contrib/ecalhdf5/src/eh5_meas_impl.h
  tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Labels: cherry-pick-to-NONE

#2372 [core] Revert previous changes based on sanitizer findings
  ecal/core/src/ecal_globals.cpp
  ecal/core/src/ecal_globals.h
  ecal/core/src/pubsub/ecal_publisher_impl.cpp
  ecal/core/src/pubsub/ecal_publisher_impl.h
  ecal/core/src/pubsub/ecal_subscriber_impl.cpp
  ecal/core/src/pubsub/ecal_subscriber_impl.h
  ecal/core/src/registration/ecal_registration_provider.cpp
  ecal/core/src/util/ecal_thread.h
Labels: cherry-pick-to-NONE
