Repository eclipse-ecal/ecal, pull requests merged in 2025-06, with the labels that each got.

#2187 [lang] C#: Wrapped process.h
  lang/csharp/Eclipse.eCAL.Core.Samples/pubsub/blob_receive_csharp.cs
  lang/csharp/Eclipse.eCAL.Core.Samples/pubsub/blob_send_csharp.cs
  lang/csharp/Eclipse.eCAL.Core/CMakeLists.txt
  lang/csharp/Eclipse.eCAL.Core/include/clr_process.h
  lang/csharp/Eclipse.eCAL.Core/include/clr_process_severity.h
  lang/csharp/Eclipse.eCAL.Core/src/clr_process.cpp
  lang/csharp/Eclipse.eCAL.Protobuf.Samples/pubsub/person_receive_csharp.cs
  lang/csharp/Eclipse.eCAL.Protobuf.Samples/pubsub/person_send_csharp.cs
  lang/csharp/Eclipse.eCAL.String.Samples/pubsub/hello_receive_csharp.cs
  lang/csharp/Eclipse.eCAL.String.Samples/pubsub/hello_send_csharp.cs
Labels: cherry-pick-to-support/v6.0

#2201 Update rust binding link in Readme.md to rustecal
  README.md
Labels: cherry-pick-to-support/v6.0

#2199 [csharp] add a callback-based ServiceClient API and a corresponding C# sample (2)
  lang/csharp/Eclipse.eCAL.Core.Samples/pubsub/CMakeLists.txt
  lang/csharp/Eclipse.eCAL.Core.Samples/service/mirror_client_csharp.cs
  lang/csharp/Eclipse.eCAL.Core/include/service/clr_client.h
  lang/csharp/Eclipse.eCAL.Core/src/clr_client.cpp
Labels: cherry-pick-to-support/v6.0

#2205 fixed another rust link
  README.md
Labels: documentation, cherry-pick-to-support/v6.0

#2191 modified pipe_handler
  app/rec/rec_client_core/src/addons/pipe_handler.cpp
Labels: cherry-pick-to-support/v5.12, cherry-pick-to-support/v5.13, cherry-pick-to-support/v6.0
